load("//rules/testing:ide_starter.bzl", "IDE_ID", "ide_starter_test")

ide_starter_test(
    name = "BazelCoverageTest",
    src = "BazelCoverageTest.kt",
    classname = "org.jetbrains.bazel.run.coverage.BazelCoverageTest",
    ide_ids = [IDE_ID.IC],
)
