// A tiny code generator: writes one header per NAME=VALUE argument into an output directory.
//
//   header_gen <out_dir> <include_prefix> NAME=VALUE...
//
// produces <out_dir>/<include_prefix>/<name>.h, each defining <PREFIX>_<NAME> as VALUE.

#include <cctype>
#include <cstdio>
#include <fstream>
#include <string>
#include <sys/stat.h>

static std::string upper(std::string s) {
  for (char& c : s) c = static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
  return s;
}

int main(int argc, char** argv) {
  if (argc < 3) {
    return 2;
  }
  const std::string out_dir = argv[1];
  const std::string prefix = argv[2];
  const std::string dir = out_dir + "/" + prefix;

  if (mkdir(dir.c_str(), 0755) != 0) {
    std::perror(("mkdir " + dir).c_str());
    return 1;
  }

  for (int i = 3; i < argc; ++i) {
    const std::string spec = argv[i];
    const std::string::size_type eq = spec.find('=');
    if (eq == std::string::npos) {
      return 2;
    }
    const std::string name = spec.substr(0, eq);
    const std::string value = spec.substr(eq + 1);

    std::ofstream out(dir + "/" + name + ".h");
    out << "// generated by header_gen; do not edit\n"
        << "#pragma once\n"
        << "#define " << upper(prefix) << "_" << upper(name) << " " << value << "\n";
    if (!out) {
      std::fprintf(stderr, "failed to write %s/%s.h\n", dir.c_str(), name.c_str());
      return 1;
    }
  }
  return 0;
}
