load("@//rules/testing:intellij.bzl", "kt_intellij_junit4_test")

kt_intellij_junit4_test(
    name = "ProjectViewTest",
    src = "ProjectViewTest.kt",
    tags = ["exclusive"],
    deps = [
        "//plugin-bazel",
    ],
)

kt_intellij_junit4_test(
    name = "ProjectViewImportTest",
    src = "ProjectViewImportTest.kt",
    tags = ["exclusive"],
    deps = [
        "//plugin-bazel",
    ],
)

kt_intellij_junit4_test(
    name = "ProjectViewTryImportTest",
    src = "ProjectViewTryImportTest.kt",
    tags = ["exclusive"],
    deps = [
        "//plugin-bazel",
    ],
)
