load("@rules_java//java:java_library.bzl", "java_library")

java_library(
    name = "app",
    srcs = ["App.java"],
    deps = [
        "//lib_java",
        "//lib_java_variant",
        "//lib_kotlin",
        "//lib_kotlin_variant",
        "//sourceless_jar",
    ],
)
