load("@//rules/testing:intellij.bzl", "kt_intellij_junit4_test")

kt_intellij_junit4_test(
    name = "ProjectViewSectionCompletionContributorTest",
    src = "ProjectViewSectionCompletionContributorTest.kt",
    tags = ["exclusive"],
    deps = [
        "//plugin-bazel",
    ],
)

kt_intellij_junit4_test(
    name = "ProjectViewSectionItemCompletionContributorTest",
    src = "ProjectViewSectionItemCompletionContributorTest.kt",
    tags = ["exclusive"],
    deps = [
        "//plugin-bazel"
    ],
)
