load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")

py_binary(
	name = "binary",
	srcs = ["bin.py"],
	main = "bin.py",
)

py_library(
	name = "library",
	srcs = ["lib.py"],
)

py_test(
	name = "test",
	srcs = ["test.py"],
)
