load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_binary", "kt_jvm_library", "kt_jvm_test")

kt_jvm_binary(
    name = "binary",
    srcs = ["Bin.kt"],
    main_class = "Bin"
)

kt_jvm_library(
    name = "library",
    srcs = ["Lib.kt"]
)

kt_jvm_test(
    name = "test",
    srcs = ["Test.kt"]
)
