load("@//rules/testing:junit5.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "UnfilteredCompilerOptionsTest",
    size = "small",
    src = "UnfilteredCompilerOptionsTest.kt",
    deps = [
           "//plugin-bsp/src/main/kotlin/org/jetbrains/plugins/bsp/impl",
    ],
)