exports_files(["FunctionAnnotatorTestData.bzl"])

exports_files(["StringAnnotatorTestData.bzl"])

exports_files(["UnusedDeclarationTestData.bzl"])

exports_files(["UnresolvedNamedArgumentsAnnotatorTestData.bzl"])

exports_files(["NoArgsGlobAnnotatorTestData.bzl"])

exports_files(["EmptyIncludesGlobAnnotatorTestData.bzl"])

exports_files(["EmptyUnnamedIncludesGlobAnnotatorTestData.bzl"])

exports_files(["EmptyGlobAnnotatorTestData.bzl"])

exports_files(["UnresolvedGlobPatternsAnnotatorTestData.bzl"])

exports_files(["SomeUnresolvedGlobPatternsAnnotatorTestData.bzl"])

exports_files(["EmptyGlobAllowedAnnotatorTestData.bzl"])

exports_files(["UnresolvedGlobPatternsAllowedAnnotatorTestData.bzl"])
