exports_files(["FunctionAnnotatorTestData.bzl"])

exports_files(["StringAnnotatorTestData.bzl"])

exports_files(["UnusedDeclarationTestData.bzl"])

exports_files(["UnresolvedNamedArgumentsAnnotatorTestData.bzl"])
