exports_files(["FunctionAnnotatorTestData.bzl"])

exports_files(["StringAnnotatorTestData.bzl"])

exports_files(["UnusedDeclarationTestData.bzl"])

exports_files(["UnresolvedNamedArgumentsAnnotatorTestData.bzl"])

exports_files(["UnresolvedSrcsAnnotatorTestData.bzl"])

exports_files(["MultipleUnresolvedSrcsAnnotatorTestData.bzl"])

exports_files(["SomeUnresolvedSrcsAnnotatorTestData.bzl"])

exports_files(["SomeUnresolvedKtSrcsAnnotatorTestData.bzl"])

exports_files(["EmptyGlobAnnotatorTestData.bzl"])

exports_files(["UnresolvedGlobAnnotatorTestData.bzl"])
