load("@//rules/testing:intellij.bzl", "kt_intellij_junit4_test")

kt_intellij_junit4_test(
    name = "BspJVMRunLineMarkerContributorTest",
    src = "BspJVMRunLineMarkerContributorTest.kt",
    deps = [
        "//plugin-bazel:intellij-bazel",
        "//plugin-bsp:intellij-bsp",
    ],
)
