load("@rules_java//java:java_library.bzl", "java_library")

java_library(
    name = "B",
    srcs = [
        "B.java",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//src/main/com/example/c:C",
    ],
)
