load("@//rules/testing:junit5.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "ProjectViewListSectionParserTest",
    size = "small",
    src = "ProjectViewListSectionParserTest.kt",
    deps = [
        "//server/executioncontext/projectview/src/main/kotlin/org/jetbrains/bsp/bazel/projectview/parser/sections",
    ],
)

kt_junit5_test(
    name = "ProjectViewExcludableListSectionParserTest",
    size = "small",
    src = "ProjectViewExcludableListSectionParserTest.kt",
    deps = [
        "//server/executioncontext/projectview/src/main/kotlin/org/jetbrains/bsp/bazel/projectview/parser/sections",
    ],
)

kt_junit5_test(
    name = "ProjectViewSingletonSectionParserTest",
    size = "small",
    src = "ProjectViewSingletonSectionParserTest.kt",
    deps = [
        "//server/executioncontext/projectview/src/main/kotlin/org/jetbrains/bsp/bazel/projectview/parser/sections",
    ],
)
