load("@rules_java//java:java_library.bzl", "java_library")

java_library(
    name = "default_package_app",
    srcs = ["DefaultPackageApp.java"],
    deps = [
        "//lib_java_default_package",
        "//lib_kotlin_default_package",
    ],
)
