load("//rules/kotlin:macros.bzl", "kt_library")

kt_library(
    name = "logger",
    visibility = ["//visibility:public"],
    exports = [
        "//server/logger/src/main/kotlin/org/jetbrains/bazel/logger",
    ],
)
