load("@rules_android//rules:rules.bzl", "android_binary")

android_binary(
    name = "app",
    manifest = "AndroidManifest.xml",
    deps = ["//server/src/main/java/com/example/myapplication:lib"],
)
