#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DOCKER_DIR="$SCRIPT_DIR/../docker/nativelink"
CERT_DIR="$DOCKER_DIR/certs"
CACHE_DIR="$HOME/.cache/nativelink"
CONTAINER_NAME="bazel-rbe-local"
ULTIMATE_ROOT="$SCRIPT_DIR/../../../.."
BAZELRC_USER="$ULTIMATE_ROOT/.bazelrc-user.bazelrc"

mkdir -p "$CACHE_DIR"

echo "Building NativeLink image..."
docker build --platform=linux/amd64 -t nativelink-local "$DOCKER_DIR"

docker rm -f "$CONTAINER_NAME" 2>/dev/null || true

echo "Starting NativeLink with mTLS..."
docker run --init --rm -d \
  --platform=linux/amd64 \
  --name "$CONTAINER_NAME" \
  -v "$CACHE_DIR:/data" \
  -p 50051:50051 \
  nativelink-local

for i in $(seq 1 30); do
  if docker logs "$CONTAINER_NAME" 2>&1 | grep -q "Ready, listening on 0.0.0.0:50051"; then
    echo "NativeLink RBE ready at grpcs://localhost:50051 (mTLS enabled)"

    cat > "$BAZELRC_USER" <<EOF
# Auto-generated by start-local-rbe.sh — do not edit.
# Run stop-local-rbe.sh to remove this file and stop the server.
common --remote_cache=
build --tls_certificate=$CERT_DIR/ca.pem
build --tls_client_certificate=$CERT_DIR/client.pem
build --tls_client_key=$CERT_DIR/client-key.pem
build --remote_executor=grpcs://localhost:50051
build --remote_default_exec_properties=OSFamily=Linux
build --jobs=HOST_CPUS*.5
build --remote_timeout=600
EOF
    echo "Written $BAZELRC_USER"
    exit 0
  fi
  sleep 1
done

echo "ERROR: NativeLink failed to start within 30s"
docker logs "$CONTAINER_NAME"
exit 1
