load("//rules/testing:ide_starter.bzl", "ide_starter_test")

ide_starter_test(
    name = "BazelProjectModelModifierTest",
    size = "large",
    src = "BazelProjectModelModifierTest.kt",
    classname = "org.jetbrains.bazel.flow.modify.BazelProjectModelModifierTest",
    deps = [
        "//plugin-bazel/src/test/kotlin/org/jetbrains/bazel/ideStarter:baseTest",
    ],
)
