load("//rules/testing:ide_starter.bzl", "IDE_ID", "ide_starter_test")

ide_starter_test(
    name = "BazelProjectModelModifierTest",
    src = "BazelProjectModelModifierTest.kt",
    classname = "org.jetbrains.bazel.flow.modify.BazelProjectModelModifierTest",
    ide_ids = [IDE_ID.IC],
)
