load("@rules_go//go:def.bzl", "go_library", "go_binary", "go_test")

go_binary(
	name = "binary",
	srcs = ["bin.go"],
)

go_library(
	name = "library",
    srcs = ["lib.go"],
)

go_test(
	name = "test",
	srcs = ["test.go"],
)
