load("@//rules/testing:junit5.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "EnvironmentCreatorTest",
    size = "small",
    src = "EnvironmentCreatorTest.kt",
    deps = [
        "//server/install/src/main/kotlin/org/jetbrains/bsp/bazel/install",
    ],
)
