load("@//server/rules/kotlin:junit5.bzl", "kt_test")

kt_test(
    name = "EnvironmentCreatorTest",
    size = "small",
    src = "EnvironmentCreatorTest.kt",
    deps = [
        "//server/install/src/main/kotlin/org/jetbrains/bsp/bazel/install",
    ],
)
