package org.jetbrains.bazel.redcodes

import com.intellij.openapi.application.readAction
import com.intellij.openapi.roots.ProjectFileIndex
import io.kotest.matchers.shouldBe
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.runBlocking
import org.jetbrains.bazel.config.rootDir
import org.jetbrains.bazel.test.framework.BazelTestApplication
import org.jetbrains.bazel.test.framework.bazelProjectFixture
import org.junit.jupiter.api.Test

@BazelTestApplication
class AliasMacroTest {

  private val project by bazelProjectFixture("redcodes/alias_macro")

  @Test
  fun `check that targets generated by macro and referred to by alias are imported`(): Unit = runBlocking(Dispatchers.Default) {
    // given
    val mainFile = project.rootDir
    val mainJava = checkNotNull(mainFile.findChild("Main.java"))

    // when
    val projectFileIndex = ProjectFileIndex.getInstance(project)
    val module = readAction { projectFileIndex.getModuleForFile(mainJava) }

    // then
    checkNotNull(module) { "Can't find a module that contains Main.java, is the target not imported?" }
    module.name shouldBe "macro_impl"
  }
}
