package org.jetbrains.bazel.redcodes

import com.intellij.openapi.application.readAction
import com.intellij.openapi.roots.ProjectFileIndex
import com.intellij.testFramework.junit5.fixture.projectFixture
import com.intellij.testFramework.junit5.fixture.tempPathFixture
import io.kotest.matchers.shouldBe
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.runBlocking
import org.jetbrains.bazel.config.rootDir
import org.jetbrains.bazel.test.framework.BazelTestApplication
import org.jetbrains.bazel.test.framework.bazelSyncCodeInsightFixture
import org.junit.jupiter.api.Test

@BazelTestApplication
class AliasMacroTest {

  private val projectFixture = projectFixture(openAfterCreation = true)
  private val tempDir = tempPathFixture()
  private val fixture by bazelSyncCodeInsightFixture(projectFixture, tempDir)

  @Test
  fun `check that targets generated by macro and referred to by alias are imported`() = runBlocking(Dispatchers.Default) {
    // given
    fixture.copyBazelTestProject("redcodes/alias_macro")
    fixture.performBazelSync()
    val project = fixture.project
    val mainFile = project.rootDir
    val mainJava = checkNotNull(mainFile.findChild("Main.java"))

    // when
    val projectFileIndex = ProjectFileIndex.getInstance(project)
    val module = readAction { projectFileIndex.getModuleForFile(mainJava) }

    // then
    checkNotNull(module) { "Can't find a module that contains Main.java, is the target not imported?" }
    module.name shouldBe "macro_impl"
  }
}
