load("@//rules/testing:junit5.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "WorkspaceContextConstructorTest",
    size = "small",
    src = "WorkspaceContextConstructorTest.kt",
    associates = [
        "//server/executioncontext/workspacecontext/src/main/kotlin/org/jetbrains/bsp/bazel/workspacecontext",
    ],
)

kt_junit5_test(
    name = "BazelBinarySpecMapperTest",
    size = "small",
    src = "BazelBinarySpecMapperTest.kt",
    associates = [
        "//server/executioncontext/workspacecontext/src/main/kotlin/org/jetbrains/bsp/bazel/workspacecontext",
    ],
)

kt_junit5_test(
    name = "BuildFlagsSpecMapperTest",
    size = "small",
    src = "BuildFlagsSpecMapperTest.kt",
    associates = [
        "//server/executioncontext/workspacecontext/src/main/kotlin/org/jetbrains/bsp/bazel/workspacecontext",
    ],
)

kt_junit5_test(
    name = "AllowManualTargetsSyncSpecMapperTest",
    size = "small",
    src = "AllowManualTargetsSyncSpecMapperTest.kt",
    associates = [
        "//server/executioncontext/workspacecontext/src/main/kotlin/org/jetbrains/bsp/bazel/workspacecontext",
    ],
)

kt_junit5_test(
    name = "TargetsSpecMapperTest",
    size = "small",
    src = "TargetsSpecMapperTest.kt",
    associates = [
        "//server/executioncontext/workspacecontext/src/main/kotlin/org/jetbrains/bsp/bazel/workspacecontext",
    ],
)

kt_junit5_test(
    name = "ImportDepthSpecMapperTest",
    size = "small",
    src = "ImportDepthSpecMapperTest.kt",
    associates = [
        "//server/executioncontext/workspacecontext/src/main/kotlin/org/jetbrains/bsp/bazel/workspacecontext",
    ],
)

kt_junit5_test(
    name = "DirectoriesSpecExtractorTest",
    size = "small",
    src = "DirectoriesSpecExtractorTest.kt",
    associates = [
        "//server/executioncontext/workspacecontext/src/main/kotlin/org/jetbrains/bsp/bazel/workspacecontext",
    ],
)

kt_junit5_test(
    name = "DefaultWorkspaceContextProviderTest",
    size = "small",
    src = "DefaultWorkspaceContextProviderTest.kt",
    associates = [
        "//server/executioncontext/workspacecontext/src/main/kotlin/org/jetbrains/bsp/bazel/workspacecontext",
    ],
)
