filegroup(
    name = "StarlarkEmptyGlobAllowEmptyQuickFixTestData",
    srcs = [
        "EmptyGlob.bzl",
        "EmptyGlob.bzl.after",
    ],
    visibility = ["//plugin-bazel/src/test:__subpackages__"],
)

filegroup(
    name = "StarlarkEmptyGlobNotAllowedAllowEmptyQuickFixTestData",
    srcs = [
        "EmptyGlobNotAllowed.bzl",
        "EmptyGlobNotAllowed.bzl.after",
    ],
    visibility = ["//plugin-bazel/src/test:__subpackages__"],
)

filegroup(
    name = "StarlarkUnresolvedGlobAllowEmptyQuickFixTestData",
    srcs = [
        "UnresolvedGlob.bzl",
        "UnresolvedGlob.bzl.after",
    ],
    visibility = ["//plugin-bazel/src/test:__subpackages__"],
)
