java_library(
    name = "a",
    srcs = glob([
        "ClassA.java",
        "Main.java",
    ]),
)

java_library(
    name = "b",
    srcs = glob([
        "ClassB.java",
        "Main.java",
    ]),
)
