load("//rules/kotlin:macros.bzl", "kt_library")

kt_library(
    name = "commons",
    visibility = ["//visibility:public"],
    exports = [
        "//server/commons/src/main/kotlin/org/jetbrains/bazel/commons",
    ],
)
