load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "commons",
    visibility = ["//visibility:public"],
    exports = [
        "//server/commons/src/main/kotlin/org/jetbrains/bsp/bazel/commons",
    ],
)
