java_library(
    name = "util",
    srcs = glob(["TestUtil.java"]),
)

java_library(
    name = "a",
    srcs = glob([
        "ClassA.java",
        "TestUtil.java",
    ]),
)

java_library(
    name = "b",
    srcs = glob([
        "ClassB.java",
        "TestUtil.java",
    ]),
)
