java_binary(
    name = "MavenPublisher",
    srcs = [
        "ByteStreams.java",
        "MavenPublisher.java",
    ],
    javacopts = [
        "-source",
        "8",
        "-target",
        "8",
    ],
    main_class = "org.jetbrains.bazel.MavenPublisher",
    visibility = ["//visibility:public"],
)
