load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "my_java_lib",
    srcs = [
        "MyMain1.java",
        "MyMain2.java",
    ],
    visibility = ["//visibility:public"],
)
