load("//rules/testing:junit5.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "PathExtensionTest",
    src = "PathExtensionTest.kt",
    deps = [
        "//plugin-bsp/src/main/kotlin/org/jetbrains/plugins/bsp/utils",
    ],
)

kt_junit5_test(
    name = "BspURLEncoderTest",
    src = "BspURLEncoderTest.kt",
    deps = [
        "//plugin-bsp/src/main/kotlin/org/jetbrains/plugins/bsp/utils",
    ],
)
