load("@//rules/testing:intellij.bzl", "kt_intellij_junit4_test")

kt_intellij_junit4_test(
    name = "IdeaVFSUtilTest",
    src = "IdeaVFSUtilTest.kt",
    deps = [
        "//plugin-bazel",
    ],
)
