java_library(
    name = "bsp_export",
    visibility = ["//visibility:public"],
    exports = [
        "//server/commons",
        "//server/install:install-lib",
        "//server/server/src/main/kotlin/org/jetbrains/bazel/server",
    ],
)
