load("//rules/testing:junit5.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "PathExtensionTest",
    src = "PathExtensionTest.kt",
    deps = [
        "//plugin-bazel/src/main/kotlin/org/jetbrains/bazel/utils",
    ],
)

kt_junit5_test(
    name = "StringUtilsTest",
    src = "StringUtilsTest.kt",
    deps = [
        "//plugin-bazel/src/main/kotlin/org/jetbrains/bazel/utils",
    ],
)

kt_junit5_test(
    name = "BspURLEncoderTest",
    src = "BspURLEncoderTest.kt",
    deps = [
        "//plugin-bazel/src/main/kotlin/org/jetbrains/bazel/utils",
    ],
)
