load("//rules/testing:junit5.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "PathUtilTest",
    src = "PathUtilTest.kt",
    tags = ["exclusive"],
    deps = [
        "//plugin-bazel/src/main/kotlin/org/jetbrains/bazel/utils",
    ],
)

kt_junit5_test(
    name = "StringUtilsTest",
    src = "StringUtilsTest.kt",
    tags = ["exclusive"],
    deps = [
        "//plugin-bazel/src/main/kotlin/org/jetbrains/bazel/utils",
    ],
)
