#
# This file is based on Bazel plugin for IntelliJ by The Bazel Authors, licensed under Apache-2.0;
# It was modified by JetBrains s.r.o. and contributors
#

load(
    "//:build-visibility.bzl",
    "create_common_plugins_package",
)

licenses(["notice"])

create_common_plugins_package()
