load("//rules/testing:ide_starter.bzl", "ide_starter_test")

ide_starter_test(
    name = "CompiledSourceCodeInsideJarExcludeTest",
    size = "large",
    src = "CompiledSourceCodeInsideJarExcludeTest.kt",
    classname = "org.jetbrains.bazel.languages.java.CompiledSourceCodeInsideJarExcludeTest",
    deps = [
        "//plugin-bazel/src/test/kotlin/org/jetbrains/bazel/ideStarter:baseTest",
    ],
)
