load("//rules/testing:ide_starter.bzl", "IDE_ID", "ide_starter_test")

ide_starter_test(
    name = "CompiledSourceCodeInsideJarExcludeTest",
    src = "CompiledSourceCodeInsideJarExcludeTest.kt",
    ide_ids = [IDE_ID.IC],
)
