load("@rules_java//java:java_library.bzl", "java_library")

# In project scope (a root in .bazelproject) -> imported as a source MODULE.
java_library(
    name = "A",
    srcs = ["A.java"],
    visibility = ["//visibility:public"],
)
