load("//rules/testing:junit5.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "ArgumentParserTest",
    src = "ArgumentParserTest.kt",
    deps = [
        "//plugin-bazel/src/main/kotlin/org/jetbrains/bazel/run",
    ],
)
