load("@//rules/testing:intellij.bzl", "kt_intellij_junit4_test")

kt_intellij_junit4_test(
    name = "ProjectViewAnnotatorTest",
    src = "ProjectViewAnnotatorTest.kt",
    tags = ["exclusive"],
    deps = ["//plugin-bazel"],
)
