load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "testkit-client",
    visibility = ["//visibility:public"],
    exports = [
        "//bsp-testkit2/bsp-testkit/client",
    ],
)

kt_jvm_library(
    name = "bazel-testkit-client",
    visibility = ["//visibility:public"],
    exports = [
        "//bsp-testkit2/bsp-testkit/client/bazel",
    ],
)
