bazel_dep(name = "rules_kotlin", version = "2.2.2")
bazel_dep(name = "bundled")
local_path_override(
    module_name = "bundled",
    path = "subproject",
)

bazel_dep(name = "hermetic_cc_toolchain", version = "4.1.0")

toolchains = use_extension("@hermetic_cc_toolchain//toolchain:ext.bzl", "toolchains")
use_repo(toolchains, "zig_sdk")
