load("@//rules/testing:junit5.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "CliOptionsProviderTest",
    size = "small",
    src = "CliOptionsProviderTest.kt",
    deps = [
        "//plugin-bazel/install/src/main/kotlin/org/jetbrains/bsp/bazel/install/cli",
    ],
)
