load("@//rules/testing:junit5.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "EnhancedSourceItemTypeAdapterTest",
    size = "small",
    src = "EnhancedSourceItemTypeAdapterTest.kt",
    deps = [
        "//protocol",
        "@maven//:com_google_code_gson_gson",
    ],
)
