load("@//server/rules/kotlin:junit5.bzl", "kt_test")

kt_test(
    name = "EnhancedSourceItemTypeAdapterTest",
    size = "small",
    src = "EnhancedSourceItemTypeAdapterTest.kt",
    deps = [
        "//protocol",
        "@maven//:com_google_code_gson_gson",
    ],
)
