load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "my_kt_lib",
    srcs = [
        "main1.kt",
        "main2.kt",
    ],
    visibility = ["//visibility:public"],
)
