load("@my_java//java:java_library.bzl", "java_library")
load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

java_library(
    name = "java_lib",
    srcs = ["JavaClass.java"],
)

kt_jvm_library(
    name = "kotlin_lib",
    srcs = ["KotlinClass.kt"],
)
