load("@//plugin-bazel/rules/kotlin:junit4.bzl", "junit4_kt_test")

junit4_kt_test(
    name = "BazelrcLexerTest",
    srcs = ["BazelrcLexerTest.kt"],
    deps = ["//plugin-bazel/src/test/kotlin/org/jetbrains/bazel/languages/fixtures"],
)
