load("@//rules/testing:junit5.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "BazelTestLocationHintProviderTest",
    size = "small",
    src = "BazelTestLocationHintProviderTest.kt",
    deps = [
        "//commons/src/main/kotlin/org/jetbrains/bazel/testing",
    ],
)
