load("@//rules/testing:junit5.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "ExecutionRootPathTest",
    size = "small",
    src = "ExecutionRootPathTest.kt",
    deps = [
        "//commons/src/main/kotlin/org/jetbrains/bazel/commons",
        "//plugin-bazel"
    ],
)
