alias(
    name = "sample_repo_test",
    actual = "//plugin-bazel/e2e:sample_repo_test"
)

alias(
    name = "local_jdk_test",
    actual = "//plugin-bazel/e2e:local_jdk_test"
)

alias(
    name = "remote_jdk_test",
    actual = "//plugin-bazel/e2e:remote_jdk_test"
)

alias(
    name = "cpp_project_test",
    actual = "//plugin-bazel/e2e:cpp_project_test"
)

alias(
    name = "python_project_test",
    actual = "//plugin-bazel/e2e:python_project_test"
)

alias(
    name = "kotlin_project_test",
    actual = "//plugin-bazel/e2e:kotlin_project_test"
)

alias(
    name = "kotlin_project_with_enabled_rules_test",
    actual = "//plugin-bazel/e2e:kotlin_project_with_enabled_rules_test"
)

alias(
    name = "enabled_rules_test",
    actual = "//plugin-bazel/e2e:enabled_rules_test"
)

alias(
    name = "server_downloads_bazelisk_test",
    actual = "//plugin-bazel/e2e:server_downloads_bazelisk_test"
)

alias(
    name = "rust_project_test",
    actual = "//plugin-bazel/e2e:rust_project_test"
)

alias(
    name = "android_project_test",
    actual = "//plugin-bazel/e2e:android_project_test"
)

alias(
    name = "android_kotlin_project_test",
    actual = "//plugin-bazel/e2e:android_kotlin_project_test"
)

alias(
    name = "go_project_test",
    actual = "//plugin-bazel/e2e:go_project_test"
)

alias(
    name = "java_diagnostics_test",
    actual = "//plugin-bazel/e2e:java_diagnostics_test"
)

alias(
    name = "allow_manual_targets_sync_test",
    actual = "//plugin-bazel/e2e:allow_manual_targets_sync_test"
)

alias(
    name = "partial_sync_test",
    actual = "//plugin-bazel/e2e:partial_sync_test"
)

alias(
    name = "build_and_sync_test",
    actual = "//plugin-bazel/e2e:build_and_sync_test"
)

alias(
    name = "first_phase_sync_test",
    actual = "//plugin-bazel/e2e:first_phase_sync_test"
)

alias(
    name = "nested_modules_test",
    actual = "//plugin-bazel/e2e:nested_modules_test"
)
