load("@rules_java//java:java_library.bzl", "java_library")

java_library(
    name = "base",
    srcs = ["Base.java"],
    visibility = ["//visibility:public"],
    deps = ["@dep_repo//lib:dep_lib"],
)
