load("@rules_java//java:java_library.bzl", "java_library")

java_library(
    name = "other_package",
    srcs = [
        "//src/main/org/other_package:OtherPackage.java",
    ],
    visibility = ["//visibility:public"],
)
