// Generated by JFlex 1.9.2 http://jflex.de/  (tweaked for IntelliJ platform)
// source: Bazelquery.flex

package org.jetbrains.bazel.languages.bazelquery.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.TokenType;
import com.intellij.psi.tree.IElementType;
import org.jetbrains.bazel.languages.bazelquery.elements.BazelqueryTokenTypes;

@SuppressWarnings("UnnecessaryUnicodeEscape")

class _BazelqueryLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int EXPR = 2;
  public static final int EXPR_DQ = 4;
  public static final int EXPR_SQ = 6;
  public static final int WORD_DQ = 8;
  public static final int WORD_SQ = 10;
  public static final int FLAG = 12;
  public static final int VALUE = 14;
  public static final int PRE_VALUE = 16;
  public static final int VALUE_SQ = 18;
  public static final int VALUE_DQ = 20;
  public static final int SPACE_NEEDED = 22;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6, 
     7,  7,  8,  8,  9,  9, 10, 10
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\0\1\3\22\0\1\4\1\0"+
    "\1\5\1\6\1\7\2\0\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\2\7\12\17\1\20\2\0\1\21"+
    "\2\0\1\22\33\7\1\23\1\7\1\24\1\25\1\0"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\1\37\1\54"+
    "\1\55\1\56\3\0\1\7\u0181\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\13\0\1\1\1\2\1\3\1\4\1\1\2\3\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\7\1\5\1\20\15\7\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\27\1\5"+
    "\1\31\2\32\1\33\1\34\1\0\1\4\3\0\6\7"+
    "\1\35\15\7\1\21\1\36\1\22\1\37\1\24\1\40"+
    "\1\41\2\0\1\42\1\43\3\0\11\7\1\44\4\7"+
    "\1\45\5\7\1\46\1\47\11\40\2\0\2\7\1\50"+
    "\1\7\1\51\3\7\1\52\6\7\1\53\3\7\13\40"+
    "\1\54\1\55\11\7\1\56\3\7\1\57\1\13\1\7"+
    "\13\40\1\60\1\61\3\7\1\15\1\62\1\7\1\63"+
    "\6\7\13\40\11\7\1\64\13\40\1\65\1\66\5\7"+
    "\1\67\1\70\6\40\1\71\4\40\1\7\1\20\1\72"+
    "\2\7\15\40\1\73\2\7\7\40\1\41\5\40\1\74"+
    "\1\7\14\40\1\7\12\40\1\71\1\40\1\7\6\40"+
    "\1\71\3\40\1\7\7\40\1\7\6\40\1\7\6\40"+
    "\1\7\4\40\1\7\4\40\1\7\4\40\1\7\4\40"+
    "\1\75\25\40";

  private static int [] zzUnpackAction() {
    int [] result = new int[394];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0205\0\u0263\0\u0292"+
    "\0\u02c1\0\u02f0\0\u0205\0\u0205\0\u031f\0\u0205\0\u0205\0\u0205"+
    "\0\u0205\0\u0205\0\u0205\0\u034e\0\u0205\0\u037d\0\u0292\0\u0205"+
    "\0\u03ac\0\u03db\0\u040a\0\u0439\0\u0468\0\u0497\0\u04c6\0\u04f5"+
    "\0\u0524\0\u0553\0\u0582\0\u05b1\0\u05e0\0\u060f\0\u063e\0\u066d"+
    "\0\u069c\0\u06cb\0\u0205\0\u06fa\0\u0205\0\u0729\0\u0758\0\u0205"+
    "\0\u0787\0\u07b6\0\u0205\0\u0205\0\u0292\0\u07e5\0\u0814\0\u0843"+
    "\0\u0872\0\u08a1\0\u08d0\0\u08ff\0\u092e\0\u095d\0\u098c\0\u09bb"+
    "\0\u09ea\0\u0a19\0\u0a48\0\u0a77\0\u0aa6\0\u0ad5\0\u0b04\0\u0b33"+
    "\0\u0b62\0\u0b91\0\u0bc0\0\u0bef\0\u0c1e\0\u0c4d\0\u0205\0\u0c7c"+
    "\0\u0205\0\u0cab\0\u0cda\0\u0205\0\u0758\0\u0d09\0\u0205\0\u0205"+
    "\0\u0d38\0\u0d67\0\u0d96\0\u0dc5\0\u0df4\0\u0e23\0\u0e52\0\u0e81"+
    "\0\u0eb0\0\u0edf\0\u0f0e\0\u0f3d\0\u031f\0\u0f6c\0\u0f9b\0\u0fca"+
    "\0\u0ff9\0\u031f\0\u1028\0\u1057\0\u1086\0\u10b5\0\u10e4\0\u0205"+
    "\0\u0205\0\u1113\0\u1142\0\u1171\0\u11a0\0\u11cf\0\u11fe\0\u122d"+
    "\0\u125c\0\u128b\0\u12ba\0\u12e9\0\u1318\0\u1347\0\u031f\0\u1376"+
    "\0\u031f\0\u13a5\0\u13d4\0\u1403\0\u031f\0\u1432\0\u1461\0\u1490"+
    "\0\u14bf\0\u14ee\0\u151d\0\u154c\0\u157b\0\u15aa\0\u15d9\0\u1608"+
    "\0\u1637\0\u1666\0\u1695\0\u16c4\0\u16f3\0\u1722\0\u1751\0\u1780"+
    "\0\u17af\0\u17de\0\u180d\0\u183c\0\u186b\0\u189a\0\u18c9\0\u18f8"+
    "\0\u1927\0\u1956\0\u1985\0\u19b4\0\u19e3\0\u031f\0\u1a12\0\u1a41"+
    "\0\u1a70\0\u031f\0\u031f\0\u1a9f\0\u1ace\0\u1afd\0\u1b2c\0\u1b5b"+
    "\0\u1b8a\0\u1bb9\0\u1be8\0\u1c17\0\u1c46\0\u1c75\0\u1ca4\0\u0205"+
    "\0\u0205\0\u1cd3\0\u1d02\0\u1d31\0\u031f\0\u031f\0\u1d60\0\u031f"+
    "\0\u1d8f\0\u1dbe\0\u1ded\0\u1e1c\0\u1e4b\0\u1e7a\0\u1ea9\0\u1ed8"+
    "\0\u1f07\0\u1f36\0\u1f65\0\u1f94\0\u1fc3\0\u1ff2\0\u2021\0\u2050"+
    "\0\u207f\0\u20ae\0\u20dd\0\u210c\0\u213b\0\u216a\0\u2199\0\u21c8"+
    "\0\u21f7\0\u2226\0\u031f\0\u2255\0\u2284\0\u22b3\0\u22e2\0\u2311"+
    "\0\u2340\0\u236f\0\u239e\0\u23cd\0\u23fc\0\u242b\0\u031f\0\u031f"+
    "\0\u245a\0\u2489\0\u24b8\0\u24e7\0\u2516\0\u031f\0\u031f\0\u2545"+
    "\0\u2574\0\u25a3\0\u25d2\0\u2601\0\u2630\0\u265f\0\u268e\0\u26bd"+
    "\0\u26ec\0\u271b\0\u274a\0\u031f\0\u031f\0\u2779\0\u27a8\0\u27d7"+
    "\0\u2806\0\u2835\0\u2864\0\u2893\0\u28c2\0\u28f1\0\u2920\0\u294f"+
    "\0\u297e\0\u29ad\0\u29dc\0\u2a0b\0\u031f\0\u2a3a\0\u2a69\0\u2a98"+
    "\0\u2ac7\0\u2af6\0\u2b25\0\u2b54\0\u2b83\0\u2bb2\0\u066d\0\u2be1"+
    "\0\u2c10\0\u2c3f\0\u2c6e\0\u2c9d\0\u031f\0\u2ccc\0\u2cfb\0\u2d2a"+
    "\0\u2d59\0\u2d88\0\u2db7\0\u2de6\0\u2e15\0\u2e44\0\u2e73\0\u2ea2"+
    "\0\u2ed1\0\u2f00\0\u2f2f\0\u2f5e\0\u2f8d\0\u2fbc\0\u2feb\0\u301a"+
    "\0\u3049\0\u3078\0\u30a7\0\u30d6\0\u3105\0\u3134\0\u3163\0\u3192"+
    "\0\u31c1\0\u31f0\0\u321f\0\u324e\0\u327d\0\u32ac\0\u32db\0\u330a"+
    "\0\u3339\0\u3368\0\u3397\0\u33c6\0\u33f5\0\u3424\0\u3453\0\u3482"+
    "\0\u34b1\0\u34e0\0\u350f\0\u353e\0\u356d\0\u359c\0\u35cb\0\u35fa"+
    "\0\u3629\0\u3658\0\u3687\0\u36b6\0\u36e5\0\u3714\0\u3743\0\u3772"+
    "\0\u37a1\0\u37d0\0\u37ff\0\u382e\0\u385d\0\u388c\0\u38bb\0\u38ea"+
    "\0\u3919\0\u3948\0\u3977\0\u39a6\0\u39d5\0\u3a04\0\u3a33\0\u3a62"+
    "\0\u3a91\0\u3ac0\0\u3aef\0\u3b1e\0\u031f\0\u3b4d\0\u3b7c\0\u3bab"+
    "\0\u3bda\0\u3c09\0\u3c38\0\u3c67\0\u3c96\0\u3cc5\0\u3cf4\0\u3d23"+
    "\0\u3d52\0\u3d81\0\u3db0\0\u3ddf\0\u3e0e\0\u3e3d\0\u3e6c\0\u3e9b"+
    "\0\u3eca\0\u3ef9";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[394];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\14\4\15\1\16\1\17\2\16\6\14\2\16\1\14"+
    "\1\16\1\20\1\14\2\16\1\21\16\16\1\22\10\16"+
    "\1\23\4\15\1\24\1\23\1\25\1\26\1\27\1\30"+
    "\1\23\1\31\1\32\1\33\1\34\1\25\1\35\1\36"+
    "\1\37\1\40\1\25\1\41\1\42\1\25\1\43\1\44"+
    "\1\45\2\25\1\46\1\25\1\47\1\50\5\25\1\51"+
    "\1\52\1\53\1\54\1\55\3\25\7\23\1\25\1\23"+
    "\1\27\1\30\1\23\1\31\1\32\1\33\1\34\1\25"+
    "\1\35\1\36\1\23\1\40\1\25\1\41\1\42\1\25"+
    "\1\43\1\44\1\45\2\25\1\46\1\25\1\47\1\50"+
    "\5\25\1\51\1\52\1\53\1\54\1\55\3\25\5\16"+
    "\1\56\61\16\1\57\46\16\1\60\4\0\11\60\1\61"+
    "\40\60\1\23\4\62\1\63\1\23\1\64\1\65\6\23"+
    "\2\64\1\23\1\66\1\67\1\23\32\64\1\0\1\70"+
    "\2\0\1\70\14\0\1\70\35\0\10\23\1\71\53\23"+
    "\1\72\51\23\1\73\4\74\52\73\60\0\4\15\16\0"+
    "\1\75\33\0\2\17\2\0\17\17\1\76\33\17\2\0"+
    "\1\15\1\77\101\0\1\100\102\0\1\101\13\0\1\25"+
    "\3\0\1\25\2\0\3\25\1\0\1\25\2\0\32\25"+
    "\7\0\1\25\3\0\1\25\2\0\1\25\1\34\1\25"+
    "\1\0\1\25\2\0\32\25\7\0\1\36\3\0\2\36"+
    "\1\0\3\36\1\0\1\36\2\0\32\36\7\0\1\25"+
    "\3\0\1\25\2\0\3\25\1\0\1\25\2\0\14\25"+
    "\1\102\7\25\1\103\5\25\7\0\1\25\3\0\1\25"+
    "\2\0\3\25\1\0\1\25\2\0\25\25\1\104\4\25"+
    "\7\0\1\25\3\0\1\25\2\0\3\25\1\0\1\25"+
    "\2\0\5\25\1\105\24\25\7\0\1\25\3\0\1\25"+
    "\2\0\3\25\1\0\1\25\2\0\27\25\1\106\2\25"+
    "\7\0\1\25\3\0\1\25\2\0\3\25\1\0\1\25"+
    "\2\0\11\25\1\107\20\25\7\0\1\25\3\0\1\25"+
    "\2\0\3\25\1\0\1\25\2\0\16\25\1\110\13\25"+
    "\7\0\1\25\3\0\1\25\2\0\3\25\1\0\1\25"+
    "\2\0\11\25\1\111\20\25\7\0\1\25\3\0\1\25"+
    "\2\0\3\25\1\0\1\25\2\0\1\25\1\112\3\25"+
    "\1\113\11\25\1\114\12\25\7\0\1\25\3\0\1\25"+
    "\2\0\3\25\1\0\1\25\2\0\2\25\1\115\1\25"+
    "\1\116\25\25\7\0\1\25\3\0\1\25\2\0\3\25"+
    "\1\0\1\25\2\0\1\25\1\117\3\25\1\120\3\25"+
    "\1\121\5\25\1\122\12\25\7\0\1\25\3\0\1\25"+
    "\2\0\3\25\1\0\1\25\2\0\5\25\1\123\24\25"+
    "\7\0\1\25\3\0\1\25\2\0\3\25\1\0\1\25"+
    "\2\0\16\25\1\124\13\25\7\0\1\25\3\0\1\25"+
    "\2\0\3\25\1\0\1\25\2\0\11\25\1\125\20\25"+
    "\2\126\2\0\1\126\1\127\2\126\1\0\46\126\2\130"+
    "\2\0\1\130\1\0\2\130\1\131\46\130\1\60\4\0"+
    "\52\60\16\0\1\132\1\0\1\133\1\134\3\0\32\133"+
    "\1\0\4\62\16\0\1\135\42\0\1\64\3\0\1\64"+
    "\2\0\3\64\1\0\1\64\2\0\32\64\7\0\1\66"+
    "\3\0\2\66\1\0\3\66\1\0\1\66\2\0\32\66"+
    "\2\0\1\62\1\136\53\0\2\71\2\0\4\71\1\137"+
    "\46\71\2\72\2\0\1\72\1\140\51\72\3\17\1\141"+
    "\17\17\1\76\33\17\2\0\1\15\132\0\1\142\32\0"+
    "\1\143\33\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\14\25\1\144\15\25\7\0\1\25\3\0"+
    "\1\25\2\0\3\25\1\0\1\25\2\0\24\25\1\145"+
    "\5\25\7\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\11\25\1\146\20\25\7\0\1\25\3\0"+
    "\1\25\2\0\3\25\1\0\1\25\2\0\20\25\1\147"+
    "\11\25\7\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\3\25\1\150\26\25\7\0\1\25\3\0"+
    "\1\25\2\0\3\25\1\0\1\25\2\0\14\25\1\151"+
    "\15\25\7\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\24\25\1\152\5\25\7\0\1\25\3\0"+
    "\1\25\2\0\3\25\1\0\1\25\2\0\16\25\1\153"+
    "\13\25\7\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\2\25\1\154\27\25\7\0\1\25\3\0"+
    "\1\25\2\0\3\25\1\0\1\25\2\0\24\25\1\155"+
    "\5\25\7\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\1\25\1\156\30\25\7\0\1\25\3\0"+
    "\1\25\2\0\3\25\1\0\1\25\2\0\25\25\1\157"+
    "\4\25\7\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\5\25\1\160\24\25\7\0\1\25\3\0"+
    "\1\25\2\0\3\25\1\0\1\25\2\0\15\25\1\161"+
    "\14\25\7\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\24\25\1\162\5\25\7\0\1\25\3\0"+
    "\1\25\2\0\3\25\1\0\1\25\2\0\2\25\1\163"+
    "\27\25\7\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\15\25\1\164\14\25\7\0\1\25\3\0"+
    "\1\25\2\0\3\25\1\0\1\25\2\0\23\25\1\165"+
    "\6\25\7\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\11\25\1\166\20\25\7\0\1\25\3\0"+
    "\1\25\2\0\3\25\1\0\1\25\2\0\23\25\1\167"+
    "\6\25\2\126\2\0\1\126\1\170\2\126\1\0\46\126"+
    "\2\130\2\0\1\130\1\0\2\130\1\171\46\130\20\0"+
    "\1\133\1\134\3\0\1\133\1\172\2\133\1\173\1\174"+
    "\1\133\1\175\4\133\1\176\2\133\1\177\1\200\1\201"+
    "\3\133\1\202\4\133\20\0\1\133\1\134\3\0\32\133"+
    "\2\0\1\62\56\0\1\17\106\0\1\203\73\0\1\204"+
    "\16\0\1\25\3\0\1\25\2\0\3\25\1\0\1\25"+
    "\2\0\20\25\1\205\1\25\1\206\7\25\7\0\1\25"+
    "\3\0\1\25\2\0\3\25\1\0\1\25\2\0\22\25"+
    "\1\207\7\25\7\0\1\25\3\0\1\25\2\0\3\25"+
    "\1\0\1\25\2\0\14\25\1\210\15\25\7\0\1\25"+
    "\3\0\1\25\2\0\3\25\1\0\1\25\2\0\23\25"+
    "\1\211\6\25\7\0\1\25\3\0\1\25\2\0\3\25"+
    "\1\0\1\25\2\0\5\25\1\212\24\25\7\0\1\25"+
    "\3\0\1\25\2\0\3\25\1\0\1\25\2\0\24\25"+
    "\1\213\5\25\7\0\1\25\3\0\1\25\2\0\3\25"+
    "\1\0\1\25\2\0\5\25\1\214\24\25\7\0\1\25"+
    "\3\0\1\25\2\0\3\25\1\0\1\25\2\0\4\25"+
    "\1\215\25\25\7\0\1\25\3\0\1\25\2\0\3\25"+
    "\1\0\1\25\2\0\5\25\1\216\24\25\7\0\1\25"+
    "\3\0\1\25\2\0\3\25\1\0\1\25\2\0\4\25"+
    "\1\217\25\25\7\0\1\25\3\0\1\25\2\0\3\25"+
    "\1\0\1\25\2\0\11\25\1\220\20\25\7\0\1\25"+
    "\3\0\1\25\2\0\3\25\1\0\1\25\2\0\20\25"+
    "\1\221\11\25\7\0\1\25\3\0\1\25\2\0\3\25"+
    "\1\0\1\25\2\0\5\25\1\222\24\25\7\0\1\25"+
    "\3\0\1\25\2\0\3\25\1\0\1\25\2\0\14\25"+
    "\1\223\15\25\7\0\1\25\3\0\1\25\2\0\3\25"+
    "\1\0\1\25\2\0\5\25\1\224\24\25\7\0\1\25"+
    "\3\0\1\25\2\0\3\25\1\0\1\25\2\0\24\25"+
    "\1\225\5\25\7\0\1\25\3\0\1\25\2\0\3\25"+
    "\1\0\1\25\2\0\17\25\1\226\12\25\7\0\1\25"+
    "\3\0\1\25\2\0\3\25\1\0\1\25\2\0\11\25"+
    "\1\227\20\25\20\0\1\133\1\134\3\0\23\133\1\230"+
    "\6\133\20\0\1\133\1\134\3\0\5\133\1\231\24\133"+
    "\20\0\1\133\1\134\3\0\27\133\1\232\2\133\20\0"+
    "\1\133\1\134\3\0\22\133\1\233\7\133\20\0\1\133"+
    "\1\134\3\0\17\133\1\234\12\133\20\0\1\133\1\134"+
    "\3\0\22\133\1\235\2\133\1\236\4\133\20\0\1\133"+
    "\1\134\3\0\1\133\1\237\20\133\1\240\7\133\20\0"+
    "\1\133\1\134\3\0\25\133\1\241\4\133\20\0\1\133"+
    "\1\134\3\0\16\133\1\242\13\133\41\0\1\243\72\0"+
    "\1\244\10\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\1\25\1\245\30\25\7\0\1\25\3\0"+
    "\1\25\2\0\3\25\1\0\1\25\2\0\4\25\1\246"+
    "\25\25\7\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\4\25\1\247\25\25\7\0\1\25\3\0"+
    "\1\25\2\0\3\25\1\0\1\25\2\0\20\25\1\250"+
    "\11\25\7\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\5\25\1\251\24\25\7\0\1\25\3\0"+
    "\1\25\2\0\3\25\1\0\1\25\2\0\22\25\1\252"+
    "\7\25\7\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\14\25\1\253\15\25\7\0\1\25\3\0"+
    "\1\25\2\0\3\25\1\0\1\25\2\0\6\25\1\254"+
    "\23\25\7\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\14\25\1\255\15\25\7\0\1\25\3\0"+
    "\1\25\2\0\3\25\1\0\1\25\2\0\23\25\1\256"+
    "\6\25\7\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\1\257\31\25\7\0\1\25\3\0\1\25"+
    "\2\0\3\25\1\0\1\25\2\0\11\25\1\260\20\25"+
    "\7\0\1\25\3\0\1\25\2\0\3\25\1\0\1\25"+
    "\2\0\20\25\1\261\11\25\7\0\1\25\3\0\1\25"+
    "\2\0\3\25\1\0\1\25\2\0\23\25\1\262\6\25"+
    "\7\0\1\25\3\0\1\25\2\0\3\25\1\0\1\25"+
    "\2\0\16\25\1\263\13\25\7\0\1\25\3\0\1\25"+
    "\2\0\3\25\1\0\1\25\2\0\2\25\1\264\27\25"+
    "\20\0\1\133\1\134\3\0\20\133\1\265\11\133\20\0"+
    "\1\133\1\134\3\0\14\133\1\266\15\133\20\0\1\133"+
    "\1\134\3\0\20\133\1\267\11\133\20\0\1\133\1\134"+
    "\3\0\1\133\1\270\30\133\20\0\1\133\1\134\3\0"+
    "\1\133\1\271\30\133\20\0\1\133\1\134\3\0\4\133"+
    "\1\272\25\133\20\0\1\133\1\134\3\0\24\133\1\273"+
    "\5\133\20\0\1\133\1\134\3\0\3\133\1\274\26\133"+
    "\20\0\1\133\1\134\3\0\17\133\1\275\12\133\20\0"+
    "\1\133\1\134\3\0\5\133\1\276\24\133\20\0\1\133"+
    "\1\134\3\0\11\133\1\277\20\133\4\0\1\300\56\0"+
    "\1\301\61\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\24\25\1\302\5\25\7\0\1\25\3\0"+
    "\1\25\2\0\3\25\1\0\1\25\2\0\5\25\1\303"+
    "\24\25\7\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\6\25\1\304\23\25\7\0\1\25\3\0"+
    "\1\25\2\0\3\25\1\0\1\25\2\0\24\25\1\305"+
    "\5\25\7\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\22\25\1\306\7\25\7\0\1\25\3\0"+
    "\1\25\2\0\3\25\1\0\1\25\2\0\23\25\1\307"+
    "\6\25\7\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\23\25\1\310\6\25\7\0\1\25\3\0"+
    "\1\25\2\0\3\25\1\0\1\25\2\0\11\25\1\311"+
    "\20\25\7\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\4\25\1\312\25\25\7\0\1\25\3\0"+
    "\1\25\2\0\3\25\1\0\1\25\2\0\20\25\1\313"+
    "\11\25\7\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\16\25\1\314\13\25\7\0\1\25\3\0"+
    "\1\25\2\0\3\25\1\0\1\25\2\0\1\25\1\315"+
    "\30\25\7\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\14\25\1\316\15\25\20\0\1\133\1\134"+
    "\3\0\5\133\1\317\24\133\20\0\1\133\1\134\3\0"+
    "\5\133\1\320\24\133\20\0\1\133\1\134\3\0\5\133"+
    "\1\321\24\133\20\0\1\133\1\134\3\0\20\133\1\322"+
    "\11\133\20\0\1\133\1\134\3\0\4\133\1\323\25\133"+
    "\20\0\1\133\1\134\3\0\5\133\1\324\24\133\20\0"+
    "\1\133\1\134\3\0\20\133\1\325\11\133\20\0\1\133"+
    "\1\134\3\0\13\133\1\326\16\133\20\0\1\133\1\134"+
    "\3\0\24\133\1\327\5\133\20\0\1\133\1\134\3\0"+
    "\22\133\1\330\7\133\20\0\1\133\1\134\3\0\26\133"+
    "\1\331\3\133\7\0\1\25\3\0\1\25\2\0\3\25"+
    "\1\0\1\25\2\0\10\25\1\332\21\25\7\0\1\25"+
    "\3\0\1\25\2\0\3\25\1\0\1\25\2\0\20\25"+
    "\1\333\11\25\7\0\1\25\3\0\1\25\2\0\3\25"+
    "\1\0\1\25\2\0\11\25\1\334\20\25\7\0\1\25"+
    "\3\0\1\25\2\0\3\25\1\0\1\25\2\0\5\25"+
    "\1\335\24\25\7\0\1\25\3\0\1\25\2\0\3\25"+
    "\1\0\1\25\2\0\14\25\1\336\15\25\7\0\1\25"+
    "\3\0\1\25\2\0\3\25\1\0\1\25\2\0\6\25"+
    "\1\337\23\25\7\0\1\25\3\0\1\25\2\0\3\25"+
    "\1\0\1\25\2\0\13\25\1\340\16\25\7\0\1\25"+
    "\3\0\1\25\2\0\3\25\1\0\1\25\2\0\7\25"+
    "\1\341\22\25\7\0\1\25\3\0\1\25\2\0\3\25"+
    "\1\0\1\25\2\0\24\25\1\342\5\25\7\0\1\25"+
    "\3\0\1\25\2\0\3\25\1\0\1\25\2\0\5\25"+
    "\1\343\24\25\20\0\1\133\1\134\3\0\3\133\1\344"+
    "\26\133\20\0\1\133\1\134\3\0\24\133\1\345\5\133"+
    "\20\0\1\133\1\134\3\0\22\133\1\346\7\133\20\0"+
    "\1\133\1\134\3\0\10\133\1\347\21\133\20\0\1\133"+
    "\1\134\3\0\11\133\1\350\20\133\20\0\1\133\1\134"+
    "\3\0\22\133\1\351\7\133\20\0\1\133\1\134\3\0"+
    "\25\133\1\352\4\133\20\0\1\133\1\134\3\0\1\133"+
    "\1\353\30\133\20\0\1\133\1\134\3\0\17\133\1\354"+
    "\12\133\20\0\1\133\1\134\3\0\30\133\1\355\1\133"+
    "\20\0\1\133\1\134\3\0\5\133\1\356\24\133\7\0"+
    "\1\25\3\0\1\25\2\0\3\25\1\0\1\25\2\0"+
    "\23\25\1\357\6\25\7\0\1\25\3\0\1\25\2\0"+
    "\3\25\1\0\1\25\2\0\23\25\1\360\6\25\7\0"+
    "\1\25\3\0\1\25\2\0\3\25\1\0\1\25\2\0"+
    "\14\25\1\361\15\25\7\0\1\25\3\0\1\25\2\0"+
    "\3\25\1\0\1\25\2\0\3\25\1\362\26\25\7\0"+
    "\1\25\3\0\1\25\2\0\3\25\1\0\1\25\2\0"+
    "\5\25\1\363\24\25\7\0\1\25\3\0\1\25\2\0"+
    "\3\25\1\0\1\25\2\0\11\25\1\364\20\25\7\0"+
    "\1\25\3\0\1\25\2\0\3\25\1\0\1\25\2\0"+
    "\7\25\1\365\22\25\7\0\1\25\3\0\1\25\2\0"+
    "\3\25\1\0\1\25\2\0\23\25\1\366\6\25\7\0"+
    "\1\25\3\0\1\25\2\0\3\25\1\0\1\25\2\0"+
    "\10\25\1\367\21\25\20\0\1\133\1\134\3\0\24\133"+
    "\1\370\5\133\20\0\1\133\1\134\3\0\5\133\1\371"+
    "\24\133\20\0\1\133\1\134\3\0\11\133\1\372\20\133"+
    "\20\0\1\373\1\134\3\0\32\133\20\0\1\133\1\134"+
    "\3\0\16\133\1\374\13\133\20\0\1\133\1\134\3\0"+
    "\1\375\31\133\20\0\1\133\1\134\3\0\24\133\1\376"+
    "\5\133\20\0\1\133\1\134\3\0\7\133\1\377\22\133"+
    "\20\0\1\u0100\1\134\3\0\32\133\20\0\1\133\1\134"+
    "\3\0\1\u0101\31\133\20\0\1\133\1\134\3\0\22\133"+
    "\1\u0102\7\133\7\0\1\25\3\0\1\25\2\0\3\25"+
    "\1\0\1\25\2\0\5\25\1\u0103\24\25\7\0\1\25"+
    "\3\0\1\25\2\0\3\25\1\0\1\25\2\0\24\25"+
    "\1\u0104\5\25\7\0\1\25\3\0\1\25\2\0\3\25"+
    "\1\0\1\25\2\0\23\25\1\u0105\6\25\7\0\1\25"+
    "\3\0\1\25\2\0\3\25\1\0\1\25\2\0\14\25"+
    "\1\u0106\15\25\7\0\1\25\3\0\1\25\2\0\3\25"+
    "\1\0\1\25\2\0\1\u0107\31\25\20\0\1\133\1\134"+
    "\3\0\1\u0108\31\133\20\0\1\133\1\134\3\0\4\133"+
    "\1\u0109\25\133\20\0\1\133\1\134\3\0\15\133\1\u010a"+
    "\14\133\20\0\1\133\1\134\3\0\3\133\1\u010b\12\133"+
    "\1\u010c\13\133\20\0\1\133\1\134\3\0\7\133\1\u010d"+
    "\22\133\20\0\1\133\1\134\3\0\17\133\1\u010e\12\133"+
    "\1\60\1\134\2\60\1\134\13\60\1\u010f\1\134\3\60"+
    "\1\u0110\31\u010f\20\0\1\133\1\134\3\0\5\133\1\u0111"+
    "\24\133\20\0\1\133\1\134\3\0\17\133\1\u0112\12\133"+
    "\20\0\1\133\1\134\3\0\6\133\1\u0113\23\133\20\0"+
    "\1\133\1\134\3\0\23\133\1\u0114\6\133\7\0\1\25"+
    "\3\0\1\25\2\0\3\25\1\0\1\25\2\0\23\25"+
    "\1\u0115\6\25\7\0\1\25\3\0\1\25\2\0\3\25"+
    "\1\0\1\25\2\0\5\25\1\u0116\24\25\7\0\1\25"+
    "\3\0\1\25\2\0\3\25\1\0\1\25\2\0\4\25"+
    "\1\u0117\25\25\20\0\1\133\1\134\3\0\4\133\1\u0118"+
    "\25\133\20\0\1\133\1\134\3\0\1\u0119\31\133\20\0"+
    "\1\133\1\134\3\0\5\133\1\u011a\24\133\20\0\1\133"+
    "\1\134\3\0\17\133\1\u011b\12\133\20\0\1\133\1\134"+
    "\3\0\17\133\1\u011c\12\133\20\0\1\133\1\134\3\0"+
    "\1\u011d\31\133\20\0\1\133\1\134\3\0\25\133\1\u011e"+
    "\4\133\1\60\4\0\13\60\1\u010f\1\u011f\3\60\32\u010f"+
    "\1\60\4\0\13\60\1\u010f\1\u011f\3\60\6\u010f\1\u0120"+
    "\23\u010f\20\0\1\133\1\134\3\0\1\u0121\31\133\20\0"+
    "\1\133\1\134\3\0\25\133\1\u0122\4\133\20\0\1\133"+
    "\1\134\3\0\11\133\1\u0123\20\133\20\0\1\133\1\134"+
    "\3\0\5\133\1\u0124\24\133\7\0\1\25\3\0\1\25"+
    "\2\0\3\25\1\0\1\25\2\0\23\25\1\u0125\6\25"+
    "\7\0\1\25\3\0\1\25\2\0\3\25\1\0\1\25"+
    "\2\0\11\25\1\u0126\20\25\20\0\1\133\1\134\3\0"+
    "\5\133\1\u0127\24\133\20\0\1\133\1\134\3\0\20\133"+
    "\1\u0128\11\133\20\0\1\133\1\134\3\0\16\133\1\u0129"+
    "\13\133\20\0\1\133\1\134\3\0\16\133\1\u012a\13\133"+
    "\20\0\1\133\1\134\3\0\4\133\1\u012b\25\133\20\0"+
    "\1\133\1\134\3\0\20\133\1\u012c\11\133\20\0\1\133"+
    "\1\134\3\0\24\133\1\u012d\5\133\1\60\4\0\13\60"+
    "\1\u010f\1\u011f\3\60\11\u010f\1\u012e\20\u010f\20\0\1\133"+
    "\1\134\3\0\20\133\1\u012f\11\133\20\0\1\133\1\134"+
    "\3\0\24\133\1\u0130\5\133\20\0\1\133\1\134\3\0"+
    "\14\133\1\u0131\15\133\20\0\1\133\1\134\3\0\1\u0132"+
    "\31\133\7\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\22\25\1\u0133\7\25\20\0\1\133\1\134"+
    "\3\0\20\133\1\u0134\11\133\20\0\1\133\1\134\3\0"+
    "\1\133\1\u0135\30\133\20\0\1\133\1\134\3\0\24\133"+
    "\1\u0136\5\133\20\0\1\133\1\134\3\0\4\133\1\u0137"+
    "\25\133\20\0\1\133\1\134\3\0\5\133\1\u0138\24\133"+
    "\20\0\1\133\1\134\3\0\10\133\1\u0139\21\133\20\0"+
    "\1\133\1\134\3\0\20\133\1\u013a\11\133\1\60\4\0"+
    "\13\60\1\u010f\1\u011f\3\60\14\u010f\1\u013b\15\u010f\20\0"+
    "\1\133\1\134\3\0\1\133\1\u013c\30\133\20\0\1\133"+
    "\1\134\3\0\20\133\1\u013d\11\133\20\0\1\133\1\134"+
    "\3\0\5\133\1\u013e\24\133\20\0\1\133\1\134\3\0"+
    "\23\133\1\u013f\6\133\7\0\1\25\3\0\1\25\2\0"+
    "\3\25\1\0\1\25\2\0\5\25\1\u0140\24\25\20\0"+
    "\1\133\1\134\3\0\23\133\1\u013e\6\133\20\0\1\133"+
    "\1\134\3\0\3\133\1\u0141\26\133\20\0\1\133\1\134"+
    "\3\0\1\133\1\u0142\30\133\20\0\1\133\1\134\3\0"+
    "\11\133\1\u0143\20\133\20\0\1\133\1\134\3\0\1\u0144"+
    "\31\133\20\0\1\133\1\134\3\0\1\133\1\u0145\30\133"+
    "\20\0\1\133\1\134\3\0\25\133\1\u0146\4\133\1\60"+
    "\4\0\13\60\1\u010f\1\u011f\3\60\5\u010f\1\u0147\24\u010f"+
    "\20\0\1\133\1\134\3\0\24\133\1\u0148\5\133\20\0"+
    "\1\133\1\134\3\0\25\133\1\u0149\4\133\1\60\1\134"+
    "\2\60\1\134\13\60\1\u010f\1\134\3\60\32\u010f\20\0"+
    "\1\133\1\134\3\0\3\133\1\u014a\26\133\7\0\1\25"+
    "\3\0\1\25\2\0\3\25\1\0\1\25\2\0\3\25"+
    "\1\u014b\26\25\20\0\1\133\1\134\3\0\13\133\1\u014c"+
    "\16\133\20\0\1\133\1\134\3\0\14\133\1\u014d\15\133"+
    "\20\0\1\133\1\134\3\0\24\133\1\u014e\5\133\20\0"+
    "\1\133\1\134\3\0\14\133\1\u014f\15\133\20\0\1\133"+
    "\1\134\3\0\23\133\1\u0150\6\133\20\0\1\133\1\134"+
    "\3\0\24\133\1\u013e\5\133\1\60\1\134\2\60\1\134"+
    "\13\60\1\u010f\1\u011f\3\60\32\u010f\20\0\1\133\1\134"+
    "\3\0\10\133\1\u013e\21\133\20\0\1\133\1\134\3\0"+
    "\24\133\1\u0151\5\133\20\0\1\133\1\134\3\0\17\133"+
    "\1\u0152\12\133\7\0\1\25\3\0\1\25\2\0\3\25"+
    "\1\0\1\25\2\0\24\25\1\u0153\5\25\20\0\1\133"+
    "\1\134\3\0\1\133\1\u0154\30\133\20\0\1\133\1\134"+
    "\3\0\1\u0155\31\133\20\0\1\133\1\134\3\0\11\133"+
    "\1\u0156\20\133\20\0\1\133\1\134\3\0\11\133\1\u0157"+
    "\20\133\20\0\1\133\1\134\3\0\5\133\1\u0158\24\133"+
    "\20\0\1\133\1\134\3\0\1\u0159\31\133\20\0\1\133"+
    "\1\134\3\0\20\133\1\u0131\11\133\7\0\1\25\3\0"+
    "\1\25\2\0\3\25\1\0\1\25\2\0\1\u015a\31\25"+
    "\20\0\1\133\1\134\3\0\7\133\1\u015b\22\133\20\0"+
    "\1\133\1\134\3\0\22\133\1\u015c\7\133\20\0\1\133"+
    "\1\134\3\0\17\133\1\u015d\12\133\20\0\1\133\1\134"+
    "\3\0\15\133\1\u015e\14\133\20\0\1\133\1\134\3\0"+
    "\1\u015f\31\133\20\0\1\133\1\134\3\0\22\133\1\u0160"+
    "\7\133\7\0\1\25\3\0\1\25\2\0\3\25\1\0"+
    "\1\25\2\0\22\25\1\u0161\7\25\20\0\1\133\1\134"+
    "\3\0\5\133\1\u0134\24\133\20\0\1\133\1\134\3\0"+
    "\5\133\1\u0162\24\133\20\0\1\133\1\134\3\0\16\133"+
    "\1\u0163\13\133\20\0\1\133\1\134\3\0\11\133\1\u0146"+
    "\20\133\20\0\1\133\1\134\3\0\24\133\1\u0164\5\133"+
    "\20\0\1\133\1\134\3\0\25\133\1\u0165\4\133\7\0"+
    "\1\25\3\0\1\25\2\0\3\25\1\0\1\25\2\0"+
    "\4\25\1\u0166\25\25\20\0\1\133\1\134\3\0\20\133"+
    "\1\u0167\11\133\20\0\1\133\1\134\3\0\1\133\1\u0168"+
    "\30\133\20\0\1\133\1\134\3\0\10\133\1\u0169\21\133"+
    "\20\0\1\133\1\134\3\0\14\133\1\u016a\15\133\7\0"+
    "\1\25\3\0\1\25\2\0\3\25\1\0\1\25\2\0"+
    "\5\25\1\u016b\24\25\20\0\1\133\1\134\3\0\17\133"+
    "\1\u016c\12\133\20\0\1\133\1\134\3\0\14\133\1\u016d"+
    "\15\133\20\0\1\133\1\134\3\0\22\133\1\u016e\7\133"+
    "\20\0\1\133\1\134\3\0\5\133\1\u016f\24\133\7\0"+
    "\1\25\3\0\1\25\2\0\3\25\1\0\1\25\2\0"+
    "\20\25\1\u0170\11\25\20\0\1\133\1\134\3\0\23\133"+
    "\1\u0171\6\133\20\0\1\133\1\134\3\0\1\u0172\31\133"+
    "\20\0\1\133\1\134\3\0\5\133\1\u0173\24\133\20\0"+
    "\1\133\1\134\3\0\1\u0174\31\133\7\0\1\25\3\0"+
    "\1\25\2\0\3\25\1\0\1\25\2\0\23\25\1\u0175"+
    "\6\25\20\0\1\133\1\134\3\0\11\133\1\u0176\20\133"+
    "\20\0\1\133\1\134\3\0\5\133\1\u0177\24\133\20\0"+
    "\1\133\1\134\3\0\1\133\1\u0178\30\133\20\0\1\133"+
    "\1\134\3\0\1\133\1\u0179\30\133\20\0\1\133\1\134"+
    "\3\0\24\133\1\u017a\5\133\20\0\1\133\1\134\3\0"+
    "\4\133\1\u017b\25\133\20\0\1\133\1\134\3\0\4\133"+
    "\1\u0134\25\133\20\0\1\133\1\134\3\0\24\133\1\u017c"+
    "\5\133\20\0\1\133\1\134\3\0\17\133\1\u017d\12\133"+
    "\20\0\1\133\1\134\3\0\7\133\1\u017e\22\133\20\0"+
    "\1\133\1\134\3\0\24\133\1\u017f\5\133\20\0\1\133"+
    "\1\134\3\0\22\133\1\u0180\7\133\20\0\1\133\1\134"+
    "\3\0\5\133\1\u0181\24\133\20\0\1\133\1\134\3\0"+
    "\22\133\1\u0134\7\133\20\0\1\133\1\134\3\0\30\133"+
    "\1\u0182\1\133\20\0\1\133\1\134\3\0\23\133\1\u0138"+
    "\6\133\20\0\1\133\1\134\3\0\1\u0183\31\133\20\0"+
    "\1\133\1\134\3\0\22\133\1\u0184\7\133\20\0\1\133"+
    "\1\134\3\0\5\133\1\u0185\24\133\20\0\1\133\1\134"+
    "\3\0\23\133\1\u0186\6\133\20\0\1\133\1\134\3\0"+
    "\17\133\1\u0187\12\133\20\0\1\133\1\134\3\0\14\133"+
    "\1\u0188\15\133\20\0\1\133\1\134\3\0\26\133\1\u0189"+
    "\3\133\20\0\1\133\1\134\3\0\5\133\1\u018a\24\133"+
    "\20\0\1\133\1\134\3\0\4\133\1\355\25\133";

  private static int [] zzUnpacktrans() {
    int [] result = new int[16168];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\13\0\1\11\1\1\1\11\4\1\2\11\1\1\6\11"+
    "\1\1\1\11\2\1\1\11\22\1\1\11\1\1\1\11"+
    "\2\1\1\11\2\1\2\11\1\0\1\1\3\0\25\1"+
    "\1\11\1\1\1\11\2\1\1\11\2\0\2\11\3\0"+
    "\24\1\2\11\11\1\2\0\73\1\2\11\311\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[394];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  protected int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  _BazelqueryLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { yybegin(FLAG);  yypushback(1);
            }
          // fall through
          case 62: break;
          case 2:
            { return TokenType.WHITE_SPACE;
            }
          // fall through
          case 63: break;
          case 3:
            { yybegin(EXPR); yypushback(1);
            }
          // fall through
          case 64: break;
          case 4:
            { return BazelqueryTokenTypes.COMMENT;
            }
          // fall through
          case 65: break;
          case 5:
            { yybegin(YYINITIAL); yypushback(1);
            }
          // fall through
          case 66: break;
          case 6:
            { yybegin(WORD_DQ); yypushback(1);
            }
          // fall through
          case 67: break;
          case 7:
            { return BazelqueryTokenTypes.UNQUOTED_WORD;
            }
          // fall through
          case 68: break;
          case 8:
            { yybegin(WORD_SQ); yypushback(1);
            }
          // fall through
          case 69: break;
          case 9:
            { return BazelqueryTokenTypes.LEFT_PAREN;
            }
          // fall through
          case 70: break;
          case 10:
            { return BazelqueryTokenTypes.RIGHT_PAREN;
            }
          // fall through
          case 71: break;
          case 11:
            { return BazelqueryTokenTypes.UNION;
            }
          // fall through
          case 72: break;
          case 12:
            { return BazelqueryTokenTypes.COMMA;
            }
          // fall through
          case 73: break;
          case 13:
            { return BazelqueryTokenTypes.EXCEPT;
            }
          // fall through
          case 74: break;
          case 14:
            { return BazelqueryTokenTypes.INTEGER;
            }
          // fall through
          case 75: break;
          case 15:
            { return BazelqueryTokenTypes.EQUALS;
            }
          // fall through
          case 76: break;
          case 16:
            { return BazelqueryTokenTypes.INTERSECT;
            }
          // fall through
          case 77: break;
          case 17:
            { return BazelqueryTokenTypes.DQ_UNFINISHED;
            }
          // fall through
          case 78: break;
          case 18:
            { return BazelqueryTokenTypes.SQ_UNFINISHED;
            }
          // fall through
          case 79: break;
          case 19:
            { yybegin(YYINITIAL); return BazelqueryTokenTypes.UNEXPECTED;
            }
          // fall through
          case 80: break;
          case 20:
            { return BazelqueryTokenTypes.UNFINISHED_FLAG;
            }
          // fall through
          case 81: break;
          case 21:
            { yybegin(YYINITIAL); return TokenType.WHITE_SPACE;
            }
          // fall through
          case 82: break;
          case 22:
            { yybegin(VALUE_DQ); yypushback(1);
            }
          // fall through
          case 83: break;
          case 23:
            { yybegin(SPACE_NEEDED); return BazelqueryTokenTypes.UNQUOTED_VAL;
            }
          // fall through
          case 84: break;
          case 24:
            { yybegin(VALUE_SQ); yypushback(1);
            }
          // fall through
          case 85: break;
          case 25:
            { yybegin(VALUE); return BazelqueryTokenTypes.EQUALS;
            }
          // fall through
          case 86: break;
          case 26:
            { yybegin(SPACE_NEEDED); return BazelqueryTokenTypes.UNFINISHED_VAL;
            }
          // fall through
          case 87: break;
          case 27:
            { yybegin(YYINITIAL); yypushback(1); return BazelqueryTokenTypes.MISSING_SPACE;
            }
          // fall through
          case 88: break;
          case 28:
            { yybegin(YYINITIAL); return BazelqueryTokenTypes.WHITE_SPACE;
            }
          // fall through
          case 89: break;
          case 29:
            { return BazelqueryTokenTypes.IN;
            }
          // fall through
          case 90: break;
          case 30:
            { yybegin(EXPR); return BazelqueryTokenTypes.DQ_EMPTY;
            }
          // fall through
          case 91: break;
          case 31:
            { yybegin(EXPR); return BazelqueryTokenTypes.SQ_EMPTY;
            }
          // fall through
          case 92: break;
          case 32:
            { yybegin(SPACE_NEEDED); return BazelqueryTokenTypes.FLAG_NO_VAL;
            }
          // fall through
          case 93: break;
          case 33:
            { yybegin(PRE_VALUE); yypushback(1); return BazelqueryTokenTypes.FLAG;
            }
          // fall through
          case 94: break;
          case 34:
            { yybegin(SPACE_NEEDED); return BazelqueryTokenTypes.SQ_VAL;
            }
          // fall through
          case 95: break;
          case 35:
            { yybegin(SPACE_NEEDED); return BazelqueryTokenTypes.DQ_VAL;
            }
          // fall through
          case 96: break;
          case 36:
            { return BazelqueryTokenTypes.LET;
            }
          // fall through
          case 97: break;
          case 37:
            { return BazelqueryTokenTypes.SET;
            }
          // fall through
          case 98: break;
          case 38:
            { yybegin(EXPR); return BazelqueryTokenTypes.DQ_WORD;
            }
          // fall through
          case 99: break;
          case 39:
            { yybegin(EXPR); return BazelqueryTokenTypes.SQ_WORD;
            }
          // fall through
          case 100: break;
          case 40:
            { return BazelqueryTokenTypes.ATTR;
            }
          // fall through
          case 101: break;
          case 41:
            { return BazelqueryTokenTypes.DEPS;
            }
          // fall through
          case 102: break;
          case 42:
            { return BazelqueryTokenTypes.KIND;
            }
          // fall through
          case 103: break;
          case 43:
            { return BazelqueryTokenTypes.SOME;
            }
          // fall through
          case 104: break;
          case 44:
            { return BazelqueryTokenTypes.BAZEL_NO_SPACE;
            }
          // fall through
          case 105: break;
          case 45:
            { return BazelqueryTokenTypes.QUERY_NO_SPACE;
            }
          // fall through
          case 106: break;
          case 46:
            { return BazelqueryTokenTypes.RDEPS;
            }
          // fall through
          case 107: break;
          case 47:
            { return BazelqueryTokenTypes.TESTS;
            }
          // fall through
          case 108: break;
          case 48:
            { return BazelqueryTokenTypes.BAZEL;
            }
          // fall through
          case 109: break;
          case 49:
            { return BazelqueryTokenTypes.QUERY;
            }
          // fall through
          case 110: break;
          case 50:
            { return BazelqueryTokenTypes.FILTER;
            }
          // fall through
          case 111: break;
          case 51:
            { return BazelqueryTokenTypes.LABELS;
            }
          // fall through
          case 112: break;
          case 52:
            { return BazelqueryTokenTypes.VISIBLE;
            }
          // fall through
          case 113: break;
          case 53:
            { return BazelqueryTokenTypes.ALLPATHS;
            }
          // fall through
          case 114: break;
          case 54:
            { return BazelqueryTokenTypes.ALLRDEPS;
            }
          // fall through
          case 115: break;
          case 55:
            { return BazelqueryTokenTypes.SIBLINGS;
            }
          // fall through
          case 116: break;
          case 56:
            { return BazelqueryTokenTypes.SOMEPATH;
            }
          // fall through
          case 117: break;
          case 57:
            { yybegin(PRE_VALUE); return BazelqueryTokenTypes.FLAG;
            }
          // fall through
          case 118: break;
          case 58:
            { return BazelqueryTokenTypes.LOADFILES;
            }
          // fall through
          case 119: break;
          case 59:
            { return BazelqueryTokenTypes.BUILDFILES;
            }
          // fall through
          case 120: break;
          case 60:
            { return BazelqueryTokenTypes.RBUILDFILES;
            }
          // fall through
          case 121: break;
          case 61:
            { return BazelqueryTokenTypes.SAME_PKG_DIRECT_RDEPS;
            }
          // fall through
          case 122: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
