package org.jetbrains.bazel.golang.workspace

import com.intellij.openapi.application.readAction
import com.intellij.workspaceModel.core.fileIndex.WorkspaceFileIndex
import io.kotest.matchers.shouldBe
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.runBlocking
import org.jetbrains.bazel.config.rootDir
import org.jetbrains.bazel.test.framework.BazelTestApplication
import org.jetbrains.bazel.test.framework.bazelProjectFixture
import org.junit.jupiter.api.Test

@BazelTestApplication
internal class GoWorkspaceModuleProjectSyncHookTest {
  private val project by bazelProjectFixture("redcodes/go_java_project")

  @Test
  fun `check that targets generated by macro and referred to by alias are imported`(): Unit = runBlocking(Dispatchers.Default) {
    // given
    val rootDir = project.rootDir
    val workspaceIndex = WorkspaceFileIndex.getInstance(project)
    readAction {
      // Source files should be indexable
      workspaceIndex.isIndexable(rootDir.findFileByRelativePath("go/src/main.go")!!) shouldBe true
      workspaceIndex.isIndexable(rootDir.findFileByRelativePath("java/src/Main.java")!!) shouldBe true
      // Random stuff just lying around shouldn't be indexed, that slows down the IDE
      workspaceIndex.isIndexable(rootDir.findFileByRelativePath("go/random.go")!!) shouldBe false
      workspaceIndex.isIndexable(rootDir.findFileByRelativePath("java/random.go")!!) shouldBe false
    }
  }
}
