load("@rules_python//python:defs.bzl", "py_binary")
py_binary(
    name = "main",
    visibility = ["//visibility:public"],
    srcs = ["main.py"],
    deps = [
        "//lib/libA",
       
    ],
)
