filegroup(
    name = "parser",
    srcs = glob([
        "**/*.bazelquery",
        "**/*.bazelqueryflags",
        "**/*.txt",
    ]),
    visibility = ["//plugin-bazel/src/test:__subpackages__"],
)
