load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "split",
    srcs = [
        "x/f1.go",
        "y/f2.go",
    ],
    importpath = "example.com/split",
    visibility = ["//visibility:public"],
)
