load("@//server/rules/kotlin:junit5.bzl", "kt_test")

kt_test(
    name = "ProjectViewExcludableListSectionGeneratorTest",
    size = "small",
    src = "ProjectViewExcludableListSectionGeneratorTest.kt",
    deps = [
        "//server/executioncontext/projectview/src/main/kotlin/org/jetbrains/bsp/bazel/projectview/generator/sections",
    ],
)

kt_test(
    name = "ProjectViewListSectionGeneratorTest",
    size = "small",
    src = "ProjectViewListSectionGeneratorTest.kt",
    deps = [
        "//server/executioncontext/projectview/src/main/kotlin/org/jetbrains/bsp/bazel/projectview/generator/sections",
    ],
)

kt_test(
    name = "ProjectViewSingletonSectionGeneratorTest",
    size = "small",
    src = "ProjectViewSingletonSectionGeneratorTest.kt",
    deps = [
        "//server/executioncontext/projectview/src/main/kotlin/org/jetbrains/bsp/bazel/projectview/generator/sections",
    ],
)
