load("@rules_java//java:defs.bzl", "java_library")

licenses(["notice"])

java_library(
    name = "runfiles",
    testonly = 1,
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
)
