load("@rules_java//java:java_library.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

java_library(
    name = "runfiles",
    testonly = 1,
    srcs = glob(["*.java"]),
)
