load("@rules_java//java:java_library.bzl", "java_library")

java_library(
    name = "usage",
    srcs = ["Usage.java"],
    deps = [
        "@maven//:org_apache_commons_commons_lang3",
        "@maven//:org_jetbrains_kotlin_kotlin_stdlib",
    ],
)
