load("//transitions:defs.bzl", "mode_java_library")

mode_java_library(
    name = "app_a",
    srcs = ["AppA.java"],
    mode = "a",
    deps = ["//lib:leaf"],
)

mode_java_library(
    name = "app_b",
    srcs = ["AppB.java"],
    mode = "b",
    deps = ["//lib:leaf"],
)
