load("@//rules/testing:junit5.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "LabelTest",
    size = "small",
    src = "LabelTest.kt",
    deps = [
        "//commons/src/main/kotlin/org/jetbrains/bazel/label",
    ],
)
