load("@//server/rules/kotlin:junit5.bzl", "kt_test")

kt_test(
    name = "FormatTest",
    size = "small",
    src = "FormatTest.kt",
    deps = [
        "//server/commons/src/main/kotlin/org/jetbrains/bsp/bazel/commons",
    ],
)
