load("@//rules/testing:junit5.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "FormatTest",
    size = "small",
    src = "FormatTest.kt",
    deps = [
        "//server/commons/src/main/kotlin/org/jetbrains/bsp/bazel/commons",
    ],
)
