load("@//server/rules/kotlin:junit5.bzl", "kt_test")

kt_test(
    name = "ProjectViewBuilderTest",
    size = "small",
    src = "ProjectViewBuilderTest.kt",
    deps = [
        "//server/executioncontext/projectview/src/main/kotlin/org/jetbrains/bsp/bazel/projectview/model",
    ],
)
