load("@//rules/testing:intellij.bzl", "kt_intellij_junit4_test")

kt_intellij_junit4_test(
    name = "StarlarkFileRenameTest",
    src = "StarlarkFileRenameTest.kt",
    deps = ["//plugin-bazel"],
)
