load("//transitions:defs.bzl", "mode_py_library")

mode_py_library(
    name = "app_a",
    srcs = ["AppA.py"],
    mode = "a",
    deps = ["//lib:leaf"],
)

mode_py_library(
    name = "app_b",
    srcs = ["AppB.py"],
    mode = "b",
    deps = ["//lib:leaf"],
)
