load("@//rules/testing:intellij.bzl", "kt_intellij_junit4_test")

kt_intellij_junit4_test(
    name = "BazeliskDownloaderTest",
    src = "BazeliskDownloaderTest.kt",
    deps = [
        "//plugin-bazel",
    ],
)
