load("@rules_java//java:java_library.bzl", "java_library")

java_library(
    name = "tagged",
    srcs = ["Tagged.java"],
    tags = ["ide-module-name=custom.module.name"],
)

java_library(
    name = "untagged",
    srcs = ["Untagged.java"],
)
