load("@rules_java//java:defs.bzl", "java_binary", "java_library", "java_test")

java_binary(
    name = "binary",
    srcs = ["Bin.java"]
)

java_library(
    name = "library",
    srcs = ["Lib.java"]
)

java_test(
    name = "test",
    srcs = ["Test.java"]
)
