load("@rules_cc//cc:defs.bzl", "cc_library", "cc_binary", "cc_test")

cc_binary(
	name = "binary",
	srcs = ["main.cpp"],
)

cc_library(
	name = "library",
    srcs = ["lib.cpp"],
)

cc_test(
	name = "test",
	srcs = ["test.cpp"],
)
