package(default_visibility = ["//visibility:public"])

java_binary(
    name = "calc_cli",
    srcs = glob(["src/main/java/**/*.java"]),
    deps = [],
    main_class = "pro.bravit.calc.cli.CalcCli",
)