load("@//server/rules/kotlin:junit5.bzl", "kt_test")

kt_test(
    name = "InstallationContextJavaPathEntityMapperTest",
    size = "small",
    src = "InstallationContextJavaPathEntityMapperTest.kt",
    associates = ["//server/executioncontext/installationcontext/src/main/kotlin/org/jetbrains/bsp/bazel/installationcontext"],
)
