load("@//rules/testing:junit5.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "InstallationContextJavaPathEntityMapperTest",
    size = "small",
    src = "InstallationContextJavaPathEntityMapperTest.kt",
    associates = ["//server/executioncontext/installationcontext/src/main/kotlin/org/jetbrains/bsp/bazel/installationcontext"],
)
