load("//rules/testing:ide_starter.bzl", "ide_starter_test")

ide_starter_test(
    name = "testRunLineMarker",
    size = "large",
    src = "RunLineMarkerTest.kt",
    classname = "org.jetbrains.bazel.ui.testRunLineMarker.RunLineMarkerTest",
    deps = [
        "//plugin-bazel/src/test/kotlin/org/jetbrains/bazel/ideStarter:baseTest",
    ],
)
