load("@my_protobuf//bazel:proto_library.bzl", "proto_library")

proto_library(
    name = "lib_a",
    srcs = ["lib_a.proto"],
    import_prefix = "my_prefix",
    visibility = ["//visibility:public"],
)
