package org.jetbrains.bazel.golang.debug

import com.intellij.openapi.util.io.toNioPathOrNull
import org.jetbrains.annotations.ApiStatus
import java.nio.file.Path
import java.util.Locale
import kotlin.io.path.Path

@ApiStatus.Internal
data class ExecutableInfo(
  val binary: Path,
  val workingDir: Path,
  val args: List<String?>,
  val envVars: Map<String, String>,
) {

  companion object {

    /**
     * Parses the content of the run script generated by `bazel run --script_path` into the [ExecutableInfo] needed to
     * attach the Go debugger.
     */
    fun fromBazelRunScript(scriptContent: String): ExecutableInfo {
      val args = scriptContent.extractArgs()
      val execRoot = scriptContent.extractExecRoot() ?: throw UnexpectedScriptContentException("Unable to read execution root from script.")
      val testSrcDir = scriptContent.extractTestSrcDir(execRoot)
      // regular binary case: <executable> [arg0 .. argN] $@
      if (testSrcDir == null) {
        if (args.size < 2) throw UnexpectedScriptContentException("Expected at least 2 arguments for regular binary. Actual args: $args")
        return ExecutableInfo(
          binary = Path(args[0]),
          workingDir = execRoot,
          args = args.drop(1).dropLast(1), // drops <executable> and $@
          envVars = emptyMap(),
        )
      }
      // test binary case: <wrapper> <executable> [arg0 .. argN] $@
      if (args.size < 3) throw UnexpectedScriptContentException("Expected at least 3 arguments for test binary. Actual args: $args")
      val workspaceName = scriptContent.extractWorkspaceName() ?: throw UnexpectedScriptContentException("Unable to read workspace name from script.")
      val runfilesEnv = scriptContent.extractRunfilesEnv(execRoot)
      val runfilesRoot = testSrcDir.resolve(workspaceName)
      val packagePath = scriptContent.extractTestTarget().orEmpty()
      return ExecutableInfo(
        binary = runfilesRoot.resolve(args[1]),
        workingDir = runfilesRoot.resolve(packagePath),
        args = args.drop(2).dropLast(1), // drops <wrapper> <executable> and $@
        envVars = runfilesEnv + ("TEST_SRCDIR" to testSrcDir.toString()),
      )
    }
  }
}

// Matches TEST_SRCDIR=<dir>
private val TEST_SRCDIR = "TEST_SRCDIR=(\\S+)".toRegex()

// Matches RUNFILES_<NAME>=<value>
private val RUNFILES_VAR = "RUNFILES_([A-Z_]+)=(\\S+)".toRegex()

// Matches TEST_TARGET=//<package_path>:<target>
private val TEST_TARGET = "TEST_TARGET=//([^:]*):(\\S+)".toRegex()

// Matches TEST_WORKSPACE=<name> - the runfiles top-level directory of the main repo (e.g. "_main" with Bzlmod).
private val TEST_WORKSPACE = "TEST_WORKSPACE=(\\S+)".toRegex()

// Matches the `cd <dir> &&` line the generated script uses to enter the Bazel execution root.
private val SCRIPT_BASE_DIR = "(?m)^\\s*cd (.+?) &&".toRegex()

// Matches a space-delimited arg list. Supports wrapping arg in single quotes.
private val ARGS = "([^\']\\S*|\'.+?\')\\s*".toRegex()

// The actual Bazel shell script uses "1", which is considered as true.
// For robustness, we include other common representations of true.
private val TRUTHY_ENV_VALUES_LOWER = listOf("true", "1", "yes", "on")

private fun String.extractArgs(): List<String> {
  val lastLine = split("\n").last().trim { it <= ' ' }
  return ARGS.findAll(lastLine).map { it.groupValues[1].trim('\'') }.toList()
}

private fun String.extractExecRoot(): Path? = SCRIPT_BASE_DIR
  .find(this)
  ?.groupValues
  ?.get(1)
  ?.trim()
  ?.toNioPathOrNull()

private fun String.extractWorkspaceName(): String? = TEST_WORKSPACE.find(this)?.groupValues?.get(1)

private fun String.extractTestSrcDir(execRoot: Path): Path? = TEST_SRCDIR
  .find(this)
  ?.groupValues[1]
  ?.let(execRoot::resolve)

private fun String.extractTestTarget(): String? = TEST_TARGET.find(this)?.groupValues?.get(1)

private fun String.extractRunfilesEnv(execRoot: Path): Map<String, String> = RUNFILES_VAR
  .findAll(this)
  .associate {
    val key = "RUNFILES_${it.groupValues[1]}"
    val value = it.groupValues[2]
    if (key == "RUNFILES_MANIFEST_ONLY" && value.isTruthyValue()) throw RunfileManifestOnlyException()
    key to execRoot.resolve(value).toString()
  }

private fun String.isTruthyValue(): Boolean {
  val normalized = trim { it <= ' ' }.lowercase(Locale.getDefault())
  return normalized in TRUTHY_ENV_VALUES_LOWER
}

@ApiStatus.Internal
class UnexpectedScriptContentException(reason: String) : Exception("Failed to parse Bazel run script. Reason: $reason")

@ApiStatus.Internal
class RunfileManifestOnlyException : Exception("Detected RUNFILES_MANIFEST_ONLY flag.")
