#!/usr/bin/env sh
. "$(git rev-parse --show-toplevel)/build/protobuf/getprotoc.sh"

script_dir="$(dirname "$0")"
gen_dir="$script_dir/../../protobuf/src/main/gen"

proto_dir="$script_dir/../../server/server/src/main/kotlin/org/jetbrains/bazel/server/sync/proto/"
protoc -I"$proto_dir" --java_out="$gen_dir" bsp_target_info.proto