package org.jetbrains.bazel.sync.workspace.graph

import org.jetbrains.annotations.ApiStatus
import org.jetbrains.bazel.info.BspTargetInfo
import org.jetbrains.bazel.label.Label
import org.jetbrains.bazel.label.SingleTarget
import org.jetbrains.bazel.label.assumeResolved
import org.jetbrains.bazel.label.isCompile
import org.jetbrains.bazel.label.label

@ApiStatus.Internal
class DependencyGraph(
  rootTargets: Set<Label> = emptySet(),
  val idToTargetInfo: Map<Label, BspTargetInfo.TargetInfo> = emptyMap(),
) {
  private val rootTargets: MutableSet<Label> = rootTargets.toHashSet()
  private val idToTransitiveDependencies = HashMap<Label, Set<BspTargetInfo.TargetInfo>>()

  init {
    idToTargetInfo.entries.forEach { (id, target) ->
      if (target.generatorName.isNotEmpty()) {
        val generatorTarget = id.assumeResolved().copy(target = SingleTarget(target.generatorName))
        // Support macros that generate a target and refer to it by an alias, see https://youtrack.jetbrains.com/issue/BAZEL-3048
        // Aliases generated by macros can appear in rootTargets. But the aspect isn't run on aliases, so we can't get the target it refers to without a query.
        // However, every target generated by a macro has the original macro name in .generatorName.
        // We use that here to link the alias to its actual target in the graph, without an additional Bazel query invocation.
        if (generatorTarget in rootTargets && generatorTarget !in idToTargetInfo) {
          this.rootTargets.add(id)
        }
      }
    }
  }

  private fun calculateTransitiveDependenciesForTarget(targetInfo: BspTargetInfo.TargetInfo): Set<BspTargetInfo.TargetInfo> {
    return idToTransitiveDependencies.getOrPut(targetInfo.label()) {
      targetInfo.depsList.filter { it.isCompile() }
        .flatMap { dependency ->
          val target = idToTargetInfo[dependency.label()] ?: return@flatMap emptySet()
          calculateTransitiveDependenciesForTarget(target) + target
        }.toSet()
    }
  }

  private fun idsToTargetInfo(dependencies: Collection<Label>): Set<BspTargetInfo.TargetInfo> =
    dependencies.mapNotNull(idToTargetInfo::get).toSet()

  fun allTargetsAtDepth(
    maxDepth: Int,
    // If include runtime dependencies in traversing. Default value simulates previous behavior
    runtimeDependencies: Boolean = maxDepth < 0,
    predicate: (Label) -> Boolean = { true }
  ): Set<BspTargetInfo.TargetInfo> {
    val depth = mutableMapOf<Label, Int>()
    val toVisit = ArrayDeque<Label>()

    fun dependencies(target: Label): List<Label> {
      return idToTargetInfo[target]?.depsList?.filter {
        runtimeDependencies || it.isCompile()
      }?.map { it.label() } ?: emptyList()
    }

    fun bfs(rootTargets: Collection<Label>) {
      rootTargets.filter(predicate).forEach { target ->
        depth[target] = 0
        toVisit.add(target)
      }

      while (toVisit.isNotEmpty()) {
        val current = toVisit.removeFirst()
        val currentDepth = depth.getOrDefault(current, 0)
        if (currentDepth == maxDepth) continue
        for (dep in dependencies(current).filter(predicate)) {
          if ((depth[dep] ?: Int.MAX_VALUE) > currentDepth + 1) {
            depth[dep] = currentDepth + 1
            toVisit.addLast(dep)
          }
        }
      }
    }

    bfs(rootTargets)
    return idsToTargetInfo(depth.keys)
  }

  fun transitiveDependenciesWithoutRootTargets(target: BspTargetInfo.TargetInfo): Set<BspTargetInfo.TargetInfo> =
    target.depsList.map { it.label() }
      .filterNot { rootTargets.contains(it) }
      .flatMap(::collectTransitiveDependenciesAndAddTarget)
      .toSet()

  fun transitiveDependenciesWithoutRootTargets(targetId: Label): Set<BspTargetInfo.TargetInfo> =
    idToTargetInfo[targetId]?.let { transitiveDependenciesWithoutRootTargets(it) } ?: emptySet()

  private fun collectTransitiveDependenciesAndAddTarget(targetId: Label): Set<BspTargetInfo.TargetInfo> {
    val target = idToTargetInfo[targetId] ?: return emptySet()
    return calculateTransitiveDependenciesForTarget(target) + target
  }
}
