package org.jetbrains.bazel.sync.workspace.graph

import com.google.devtools.intellij.ideinfo.IntellijIdeInfo.TargetIdeInfo
import org.jetbrains.annotations.ApiStatus
import org.jetbrains.bazel.label.Label
import org.jetbrains.bazel.label.SingleTarget
import org.jetbrains.bazel.label.assumeResolved
import org.jetbrains.bazel.label.isCompile
import org.jetbrains.bazel.sync.workspace.snapshot.WorkspaceConfigurationId
import org.jetbrains.bazel.sync.workspace.snapshot.WorkspaceTargetKey
import org.jetbrains.bazel.sync.workspace.snapshot.toWorkspaceTargetKey

@ApiStatus.Internal
class DependencyGraph(
  rootTargets: Set<WorkspaceTargetKey> = emptySet(),
  val idToTargetInfo: Map<WorkspaceTargetKey, TargetIdeInfo> = emptyMap(),
) {

  // always add unconfigured target variant as root target
  private val rootTargets: MutableSet<WorkspaceTargetKey> =
    (rootTargets.asSequence() + rootTargets.asSequence().map { it.copy(configuration = WorkspaceConfigurationId.EMPTY) }).toHashSet()

  // index `(label, configuration) -> every WorkspaceTargetKey sharing them`
  // to flatten aspect shadow graph, this is done to provide `allTargetsAtDepth` functionality
  private val labelConfig2Keys: Map<Pair<Label, WorkspaceConfigurationId>, List<WorkspaceTargetKey>> =
    idToTargetInfo.keys.groupBy { it.label to it.configuration }

  init {
    val rootLabels = rootTargets.map { it.label }.toHashSet()
    idToTargetInfo.entries.forEach { (key, target) ->
      if (target.generatorName.isNotEmpty()) {
        val generatorTarget = key.copy(
          label = key.label.assumeResolved().copy(target = SingleTarget(target.generatorName)),
          configuration = key.configuration,
          aspectIds = key.aspectIds,
        )
        // Support macros that generate a target and refer to it by an alias, see https://youtrack.jetbrains.com/issue/BAZEL-3048
        // Aliases generated by macros can appear in rootTargets. But the aspect isn't run on aliases, so we can't get the target it refers to without a query.
        // However, every target generated by a macro has the original macro name in .generatorName.
        // We use that here to link the alias to its actual target in the graph, without an additional Bazel query invocation.
        if (generatorTarget.label in rootLabels && generatorTarget !in idToTargetInfo) {
          this.rootTargets.add(key)
        }
      }
    }
  }

  private fun idsToTargetInfo(dependencies: Collection<WorkspaceTargetKey>): Set<TargetIdeInfo> =
    dependencies.mapNotNull(idToTargetInfo::get).toSet()

  fun allTargetsAtDepth(
    maxDepth: Int,
    // If include runtime dependencies in traversing. Default value simulates previous behavior
    runtimeDependencies: Boolean = maxDepth < 0,
    predicate: (WorkspaceTargetKey) -> Boolean = { true },
  ): Set<TargetIdeInfo> {
    val depth = mutableMapOf<WorkspaceTargetKey, Int>()
    val toVisit = ArrayDeque<WorkspaceTargetKey>()

    fun dependencies(target: WorkspaceTargetKey): List<WorkspaceTargetKey> {
      val deps = idToTargetInfo[target]?.depsList ?: return emptyList()
      return deps
        .filter { runtimeDependencies || it.isCompile() }
        .flatMap { dep ->
          val depKey = dep.target.toWorkspaceTargetKey()
          labelConfig2Keys[depKey.label to depKey.configuration] ?: listOf(depKey)
        }
    }

    fun bfs(rootTargets: Collection<WorkspaceTargetKey>) {
      rootTargets.filter(predicate).forEach { target ->
        depth[target] = 0
        toVisit.add(target)
      }

      while (toVisit.isNotEmpty()) {
        val current = toVisit.removeFirst()
        val currentDepth = depth.getOrDefault(current, 0)
        if (currentDepth == maxDepth) continue
        for (dep in dependencies(current).filter(predicate)) {
          if ((depth[dep] ?: Int.MAX_VALUE) > currentDepth + 1) {
            depth[dep] = currentDepth + 1
            toVisit.addLast(dep)
          }
        }
      }
    }

    bfs(rootTargets)
    return idsToTargetInfo(depth.keys)
  }
}
