load("@//rules/testing:intellij.bzl", "kt_intellij_junit4_test")

kt_intellij_junit4_test(
    name = "BazelBinarySpecExtractorPrecedenceJunit4Test",
    src = "BazelBinarySpecExtractorPrecedenceJunit4Test.kt",
    deps = [
        "//plugin-bazel",
    ],
)
