load("@rules_java//java:java_test.bzl", "java_test")

java_test(
    name = "division_test",
    srcs = [
        "DivisionTest.java",
    ],
    test_class = "DivisionTest",
    deps = [
        "@maven//:junit_junit",
    ],
)
