load("//rules/testing:ide_starter.bzl", "ide_starter_test")

ide_starter_test(
    name = "ImportRunConfigurationsSyncHookTest",
    size = "large",
    src = "ImportRunConfigurationsSyncHookTest.kt",
    classname = "org.jetbrains.bazel.run.import.ImportRunConfigurationsSyncHookTest",
    deps = [
        "//plugin-bazel/src/test/kotlin/org/jetbrains/bazel/ideStarter:baseTest",
    ],
)
