load("@rules_java//java:java_library.bzl", "java_library")

java_library(
    name = "app",
    srcs = ["App.java"],
    deps = [
        "//lib:aggregator",
        "//lib:exported",
        "//lib:strict_consumer",
    ],
)
