#
# This file is based on Bazel plugin for IntelliJ by The Bazel Authors, licensed under Apache-2.0;
# It was modified by JetBrains s.r.o. and contributors
#
# Description:
#
# Common test utilities for IntelliJ plugins.

licenses(["notice"])

exports_files(["test_defs_kt.bzl"])
