load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "lib_kotlin",
    srcs = ["src/main/com/example/kotlinlib/KotlinLib.kt"],
    visibility = ["//visibility:public"],
)
