load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "kotlin_lib",
    srcs = [
        "src/JavaHalf.java",
        "src/KotlinHalf.kt",
    ],
    visibility = ["//visibility:public"],
)
