load("@//rules/testing:intellij.bzl", "kt_intellij_junit4_test")

kt_intellij_junit4_test(
    name = "ProjectViewLabelReferenceTest",
    src = "ProjectViewLabelReferenceTest.kt",
    tags = ["exclusive"],
    deps = ["//plugin-bazel"],
)
