load("@//server/rules/kotlin:junit5.bzl", "kt_test")

kt_test(
    name = "CliOptionsProviderTest",
    size = "small",
    src = "CliOptionsProviderTest.kt",
    deps = [
        "//server/install/src/main/kotlin/org/jetbrains/bsp/bazel/install/cli",
    ],
)
