load("@//plugin-bazel/rules/kotlin:junit4.bzl", "junit4_kt_test")

junit4_kt_test(
    name = "StarlarkCommenterTest",
    srcs = ["StarlarkCommenterTest.kt"],
    data = ["//plugin-bazel/src/test/testData/starlark/commenter"],
)
