load("@//plugin-bazel/rules/kotlin:junit4.bzl", "junit4_kt_test")

junit4_kt_test(
    name = "BazelrcCommandCompletionTest",
    srcs = ["BazelrcCommandCompletionTest.kt"],
    deps = ["//plugin-bazel/src/test/kotlin/org/jetbrains/bazel/languages/bazelrc/fixtures"],
)

junit4_kt_test(
    name = "BazelrcConfigCompletionTest",
    srcs = ["BazelrcConfigCompletionTest.kt"],
    deps = ["//plugin-bazel/src/test/kotlin/org/jetbrains/bazel/languages/bazelrc/fixtures"],
)
