load("@//rules/testing:intellij.bzl", "kt_intellij_junit4_test")

kt_intellij_junit4_test(
    name = "BazelrcCommandCompletionTest",
    src = "BazelrcCommandCompletionTest.kt",
    deps = [
        "//plugin-bazel",
        "//plugin-bazel/src/test/kotlin/org/jetbrains/bazel/languages/bazelrc/fixtures",
    ],
)

kt_intellij_junit4_test(
    name = "BazelrcConfigCompletionTest",
    src = "BazelrcConfigCompletionTest.kt",
    deps = [
        "//plugin-bazel",
        "//plugin-bazel/src/test/kotlin/org/jetbrains/bazel/languages/bazelrc/fixtures",
    ],
)

kt_intellij_junit4_test(
    name = "BazelrcImportsCompletionTest",
    src = "BazelrcImportsCompletionTest.kt",
    deps = [
        "//plugin-bazel",
        "//plugin-bazel/src/test/kotlin/org/jetbrains/bazel/languages/bazelrc/fixtures",
    ],
)

kt_intellij_junit4_test(
    name = "BazelrcFlagCompletionTest",
    src = "BazelrcFlagCompletionTest.kt",
    deps = [
        "//plugin-bazel",
        "//plugin-bazel/src/test/kotlin/org/jetbrains/bazel/languages/bazelrc/fixtures",
    ],
)
