name: Build plugin with Bazel

on:
  push:
    branches:
      # Matches three-digit branches, e.g. 261, 262
      - '[0-9][0-9][0-9]'
  pull_request:
jobs:
  build:
    name: Build plugin with Bazel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Verify .iml files have corresponding BUILD files
        run: .github/workflows/check_project_structure.sh
      - name: Install Bazel
        uses: bazel-contrib/setup-bazel@0.19.0
      - name: Call Bazel build
        run: |
          bazel build //:plugin-bazel_zip
